import { apiGet } from '@/shared/api/client';
import type {
  ComplianceControlResponse,
  ComplianceGapResponse,
  ComplianceMonitoringResponse,
  ComplianceReadinessResponse,
  ComplianceRiskResponse,
  AccreditationComplianceResponse,
  AccreditationCycleResponse,
  AccreditationDeadlineResponse,
  AccreditationEvidenceReadinessResponse,
  AccreditationReportingResponse,
  AccreditationRiskResponse,
  MinistryReportingCompletenessResponse,
  MinistryReportingCycleResponse,
  MinistryReportingDeadlineResponse,
  MinistryReportingReadinessResponse,
  MinistryReportingRiskResponse,
  MinistryReportingSummaryResponse,
  ReportingCycleResponse,
  ReportingEvidenceResponse,
  ReportingProviderResponse,
  ReportingRegistryResponse,
  ReportingRuntimeShellResponse,
  ReportingSubmissionResponse,
  ReportingTemplateResponse,
  RegulatoryComplianceResponse,
  RegulatoryDeadlineResponse,
  RegulatoryDocumentResponse,
  RegulatoryReportingResponse,
  RegulatoryRequirementResponse,
  RegulatoryRiskResponse,
  RankingBenchmarkResponse,
  RankingIndicatorResponse,
  RankingReadinessResponse,
  RankingReportingResponse,
  RankingRiskResponse,
  RankingTrendResponse,
  NobdCompletenessResponse,
  NobdDatasetResponse,
  NobdQualityResponse,
  NobdReportingResponse,
  NobdRiskResponse,
  NobdSyncStatusResponse,
} from './types';

const BASE = '/api/admin/reporting-brain';

export const reportingRuntimeApi = {
  getRuntimeShell: () => apiGet<ReportingRuntimeShellResponse>(`${BASE}/runtime`),
  getRegistry: () => apiGet<ReportingRegistryResponse>(`${BASE}/runtime/registry`),
  getTemplates: () => apiGet<ReportingTemplateResponse>(`${BASE}/runtime/templates`),
  getCycles: () => apiGet<ReportingCycleResponse>(`${BASE}/runtime/cycles`),
  getSubmissions: () => apiGet<ReportingSubmissionResponse>(`${BASE}/runtime/submissions`),
  getEvidence: () => apiGet<ReportingEvidenceResponse>(`${BASE}/runtime/evidence`),
  getProviders: () => apiGet<ReportingProviderResponse>(`${BASE}/runtime/providers`),
  getMinistry: () => apiGet<MinistryReportingSummaryResponse>(`${BASE}/runtime/ministry`),
  getMinistryCycles: () => apiGet<MinistryReportingCycleResponse>(`${BASE}/runtime/ministry/cycles`),
  getMinistryDeadlines: () => apiGet<MinistryReportingDeadlineResponse>(`${BASE}/runtime/ministry/deadlines`),
  getMinistryReadiness: () => apiGet<MinistryReportingReadinessResponse>(`${BASE}/runtime/ministry/readiness`),
  getMinistryCompleteness: () => apiGet<MinistryReportingCompletenessResponse>(`${BASE}/runtime/ministry/completeness`),
  getMinistryRisks: () => apiGet<MinistryReportingRiskResponse>(`${BASE}/runtime/ministry/risks`),
  getAccreditation: () => apiGet<AccreditationReportingResponse>(`${BASE}/runtime/accreditation`),
  getAccreditationCycles: () => apiGet<AccreditationCycleResponse>(`${BASE}/runtime/accreditation/cycles`),
  getAccreditationReadiness: () => apiGet<AccreditationEvidenceReadinessResponse>(`${BASE}/runtime/accreditation/readiness`),
  getAccreditationCompliance: () => apiGet<AccreditationComplianceResponse>(`${BASE}/runtime/accreditation/compliance`),
  getAccreditationDeadlines: () => apiGet<AccreditationDeadlineResponse>(`${BASE}/runtime/accreditation/deadlines`),
  getAccreditationRisks: () => apiGet<AccreditationRiskResponse>(`${BASE}/runtime/accreditation/risks`),
  getRegulatory: () => apiGet<RegulatoryReportingResponse>(`${BASE}/runtime/regulatory`),
  getRegulatoryRequirements: () => apiGet<RegulatoryRequirementResponse>(`${BASE}/runtime/regulatory/requirements`),
  getRegulatoryCompliance: () => apiGet<RegulatoryComplianceResponse>(`${BASE}/runtime/regulatory/compliance`),
  getRegulatoryDeadlines: () => apiGet<RegulatoryDeadlineResponse>(`${BASE}/runtime/regulatory/deadlines`),
  getRegulatoryDocuments: () => apiGet<RegulatoryDocumentResponse>(`${BASE}/runtime/regulatory/documents`),
  getRegulatoryRisks: () => apiGet<RegulatoryRiskResponse>(`${BASE}/runtime/regulatory/risks`),
  getRanking: () => apiGet<RankingReportingResponse>(`${BASE}/runtime/ranking`),
  getRankingIndicators: () => apiGet<RankingIndicatorResponse>(`${BASE}/runtime/ranking/indicators`),
  getRankingReadiness: () => apiGet<RankingReadinessResponse>(`${BASE}/runtime/ranking/readiness`),
  getRankingBenchmarks: () => apiGet<RankingBenchmarkResponse>(`${BASE}/runtime/ranking/benchmarks`),
  getRankingTrends: () => apiGet<RankingTrendResponse>(`${BASE}/runtime/ranking/trends`),
  getRankingRisks: () => apiGet<RankingRiskResponse>(`${BASE}/runtime/ranking/risks`),
  getNobd: () => apiGet<NobdReportingResponse>(`${BASE}/runtime/nobd`),
  getNobdDatasets: () => apiGet<NobdDatasetResponse>(`${BASE}/runtime/nobd/datasets`),
  getNobdCompleteness: () => apiGet<NobdCompletenessResponse>(`${BASE}/runtime/nobd/completeness`),
  getNobdQuality: () => apiGet<NobdQualityResponse>(`${BASE}/runtime/nobd/quality`),
  getNobdSyncStatus: () => apiGet<NobdSyncStatusResponse>(`${BASE}/runtime/nobd/sync-status`),
  getNobdRisks: () => apiGet<NobdRiskResponse>(`${BASE}/runtime/nobd/risks`),
  getCompliance: () => apiGet<ComplianceMonitoringResponse>(`${BASE}/runtime/compliance`),
  getComplianceControls: () => apiGet<ComplianceControlResponse>(`${BASE}/runtime/compliance/controls`),
  getComplianceReadiness: () => apiGet<ComplianceReadinessResponse>(`${BASE}/runtime/compliance/readiness`),
  getComplianceGaps: () => apiGet<ComplianceGapResponse>(`${BASE}/runtime/compliance/gaps`),
  getComplianceRisks: () => apiGet<ComplianceRiskResponse>(`${BASE}/runtime/compliance/risks`),
};
