from __future__ import annotations

from dataclasses import dataclass, field
from threading import Lock

from app.core.db import get_raw_conn

try:
    import psycopg
except ImportError:  # pragma: no cover
    psycopg = None


@dataclass(frozen=True)
class EntityConfig:
    table: str
    fields: tuple[str, ...]
    required: tuple[str, ...]
    fk_fields: tuple[str, ...] = ()


ENTITY_CONFIGS: dict[str, EntityConfig] = {
    "students": EntityConfig(
        table="university_students",
        fields=("student_id", "first_name", "last_name", "email", "status", "tenant_id"),
        required=("student_id", "first_name", "last_name", "email", "status"),
    ),
    "faculty": EntityConfig(
        table="university_faculty",
        fields=("faculty_id", "first_name", "last_name", "department", "email", "status", "tenant_id"),
        required=("faculty_id", "first_name", "last_name", "department", "email", "status"),
    ),
    "faculty_contracts": EntityConfig(
        table="university_faculty_contracts",
        fields=(
            "faculty_id",
            "contract_type",
            "start_date",
            "end_date",
            "fte_ratio",
            "max_credit_hours",
            "status",
            "notes",
            "termination_reason",
            "tenant_id",
        ),
        required=(
            "faculty_id",
            "contract_type",
            "start_date",
            "fte_ratio",
            "max_credit_hours",
            "status",
        ),
        fk_fields=(),
    ),
    "faculty_contract_termination_alerts": EntityConfig(
        table="university_faculty_contract_termination_alerts",
        fields=(
            "contract_id",
            "alert_status",
            "integration_source",
            "source_entity_id",
            "tenant_id",
        ),
        required=("contract_id", "alert_status", "integration_source", "source_entity_id"),
        fk_fields=(),
    ),
    "programs": EntityConfig(
        table="university_programs",
        fields=("program_code", "title", "degree_type", "faculty", "status", "accreditation_body", "tenant_id"),
        required=("program_code", "title", "degree_type", "faculty", "status"),
    ),
    "program_sunset_alerts": EntityConfig(
        table="university_program_sunset_alerts",
        fields=("program_id", "program_code", "degree_type", "sunset_status", "alert_status", "integration_source", "source_entity_id", "tenant_id"),
        required=("program_id", "sunset_status", "alert_status", "integration_source", "source_entity_id"),
    ),
    "courses": EntityConfig(
        table="university_courses",
        fields=("course_code", "title", "credits", "program_id", "status", "syllabus_url", "tenant_id"),
        required=("course_code", "title", "credits", "program_id", "status"),
        fk_fields=("program_id",),
    ),
    "course_retirement_alerts": EntityConfig(
        table="university_course_retirement_alerts",
        fields=("course_id", "course_code", "program_id", "retirement_status", "alert_status", "integration_source", "source_entity_id", "tenant_id"),
        required=("course_id", "retirement_status", "alert_status", "integration_source", "source_entity_id"),
    ),
    "enrollments": EntityConfig(
        table="university_enrollments",
        fields=("student_id", "course_id", "semester", "status", "tenant_id"),
        required=("student_id", "course_id", "semester", "status"),
        fk_fields=("student_id", "course_id"),
    ),
    "academic_records": EntityConfig(
        table="university_academic_records",
        fields=("student_id", "course_id", "grade", "semester", "status", "notes", "tenant_id"),
        required=("student_id", "course_id", "grade", "semester", "status"),
        fk_fields=("student_id", "course_id"),
    ),
    "academic_withdrawal_alerts": EntityConfig(
        table="university_academic_withdrawal_alerts",
        fields=("record_id", "alert_type", "integration_source", "source_entity_id", "tenant_id"),
        required=("record_id", "alert_type"),
        fk_fields=(),
    ),
    "advising_sessions": EntityConfig(
        table="university_advising_sessions",
        fields=(
            "student_id",
            "advisor_id",
            "session_type",
            "status",
            "scheduled_at",
            "notes",
            "outcome",
            "meeting_link",
            "tenant_id",
        ),
        required=("student_id", "advisor_id", "session_type", "status"),
        fk_fields=(),
    ),
    "advising_support_alerts": EntityConfig(
        table="university_advising_support_alerts",
        fields=(
            "session_id",
            "student_id",
            "advisor_id",
            "session_type",
            "alert_status",
            "integration_source",
            "source_entity_id",
            "tenant_id",
        ),
        required=("session_id", "student_id", "advisor_id", "session_type", "alert_status", "integration_source", "source_entity_id"),
        fk_fields=(),
    ),
    # W68: advising no-show risk alerts
    "advising_no_show_risk_alerts": EntityConfig(
        table="university_advising_no_show_risk_alerts",
        fields=(
            "session_id",
            "student_id",
            "advisor_id",
            "session_type",
            "alert_status",
            "integration_source",
            "source_entity_id",
            "tenant_id",
        ),
        required=("session_id", "student_id", "advisor_id", "session_type", "alert_status", "integration_source", "source_entity_id"),
        fk_fields=(),
    ),
    "student_service_tickets": EntityConfig(
        table="university_student_service_tickets",
        fields=(
            "student_id",
            "category",
            "subject",
            "description",
            "priority",
            "status",
            "owner_id",
            "channel",
            "resolution_notes",
            "tenant_id",
        ),
        required=("student_id", "category", "subject", "description", "priority", "status"),
        fk_fields=(),
    ),
    "career_opportunities": EntityConfig(
        table="university_career_opportunities",
        fields=(
            "student_id",
            "title",
            "company",
            "opportunity_type",
            "status",
            "owner_id",
            "start_date",
            "notes",
            "tenant_id",
        ),
        required=("student_id", "title", "company", "opportunity_type", "status"),
        fk_fields=(),
    ),
    "career_placement_records": EntityConfig(
        table="university_career_placement_records",
        fields=(
            "student_id",
            "opportunity_id",
            "company",
            "opportunity_type",
            "status",
            "integration_source",
            "source_entity_id",
            "tenant_id",
        ),
        required=("student_id", "opportunity_id", "company", "opportunity_type", "status"),
        fk_fields=(),
    ),
    "career_stalled_opportunity_alerts": EntityConfig(
        table="university_career_stalled_opportunity_alerts",
        fields=(
            "opportunity_id",
            "student_id",
            "opportunity_type",
            "company",
            "status",
            "alert_level",
            "risk_status",
            "integration_source",
            "source_entity_id",
            "tenant_id",
        ),
        required=("opportunity_id", "student_id", "opportunity_type", "company", "status", "alert_level", "risk_status"),
        fk_fields=(),
    ),
    "financial_aid_records": EntityConfig(
        table="university_financial_aid_records",
        fields=(
            "student_id",
            "aid_type",
            "amount",
            "currency",
            "status",
            "term",
            "reviewer_id",
            "notes",
            "source_channel",
            "tenant_id",
        ),
        required=("student_id", "aid_type", "amount", "currency", "status", "term"),
        fk_fields=(),
    ),
    "financial_aid_disbursement_watches": EntityConfig(
        table="university_financial_aid_disbursement_watches",
        fields=(
            "aid_record_id",
            "student_id",
            "aid_type",
            "amount",
            "term",
            "watch_status",
            "integration_source",
            "source_entity_id",
            "tenant_id",
        ),
        required=("aid_record_id", "student_id", "aid_type", "amount", "term", "watch_status", "integration_source", "source_entity_id"),
        fk_fields=(),
    ),
    "financial_aid_disbursements": EntityConfig(
        table="university_financial_aid_disbursements",
        fields=(
            "disbursement_code",
            "aid_record_id",
            "student_id",
            "aid_type",
            "amount",
            "currency",
            "term",
            "status",
            "integration_source",
            "source_entity_id",
            "tenant_id",
        ),
        required=("disbursement_code", "aid_record_id", "student_id", "aid_type", "amount", "currency", "term", "status"),
        fk_fields=(),
    ),
    "financial_aid_disbursement_risk_alerts": EntityConfig(
        table="university_financial_aid_disbursement_risk_alerts",
        fields=(
            "aid_record_id",
            "student_id",
            "aid_type",
            "amount",
            "term",
            "alert_status",
            "integration_source",
            "source_entity_id",
            "tenant_id",
        ),
        required=("aid_record_id", "student_id", "aid_type", "alert_status", "integration_source", "source_entity_id"),
        fk_fields=(),
    ),
    "student_service_sla_alerts": EntityConfig(
        table="university_student_service_sla_alerts",
        fields=(
            "ticket_id",
            "student_id",
            "priority",
            "category",
            "alert_level",
            "status",
            "integration_source",
            "source_entity_id",
            "tenant_id",
        ),
        required=("ticket_id", "student_id", "priority", "category", "alert_level", "status"),
        fk_fields=(),
    ),
    "student_service_unresolved_alerts": EntityConfig(
        table="university_student_service_unresolved_alerts",
        fields=(
            "ticket_id",
            "student_id",
            "priority",
            "category",
            "status",
            "alert_level",
            "risk_status",
            "integration_source",
            "source_entity_id",
            "tenant_id",
        ),
        required=("ticket_id", "student_id", "priority", "category", "status", "alert_level", "risk_status"),
        fk_fields=(),
    ),
    "housing_requests": EntityConfig(
        table="university_housing_requests",
        fields=(
            "student_id",
            "request_type",
            "dormitory",
            "room_preference",
            "status",
            "manager_id",
            "notes",
            "tenant_id",
        ),
        required=("student_id", "request_type", "dormitory", "status"),
        fk_fields=(),
    ),
    "room_assignment_records": EntityConfig(
        table="university_room_assignment_records",
        fields=(
            "student_id",
            "request_id",
            "dormitory",
            "room_preference",
            "request_type",
            "status",
            "integration_source",
            "source_entity_id",
            "tenant_id",
        ),
        required=("student_id", "request_id", "dormitory", "status"),
        fk_fields=(),
    ),
    "housing_maintenance_risk_alerts": EntityConfig(
        table="university_housing_maintenance_risk_alerts",
        fields=(
            "request_id",
            "student_id",
            "dormitory",
            "request_type",
            "alert_status",
            "integration_source",
            "source_entity_id",
            "tenant_id",
        ),
        required=("request_id", "student_id", "dormitory", "alert_status", "integration_source", "source_entity_id"),
        fk_fields=(),
    ),
    "alumni_records": EntityConfig(
        table="university_alumni_records",
        fields=(
            "student_id",
            "graduation_year",
            "status",
            "engagement_type",
            "employer",
            "contact_email",
            "notes",
            "tenant_id",
        ),
        required=("student_id", "graduation_year", "status", "engagement_type"),
        fk_fields=(),
    ),
    "alumni_engagement_events": EntityConfig(
        table="university_alumni_engagement_events",
        fields=(
            "student_id",
            "record_id",
            "engagement_type",
            "graduation_year",
            "status",
            "integration_source",
            "source_entity_id",
            "tenant_id",
        ),
        required=("student_id", "record_id", "engagement_type", "status"),
        fk_fields=(),
    ),
    "alumni_disengagement_risk_alerts": EntityConfig(
        table="university_alumni_disengagement_risk_alerts",
        fields=("record_id", "student_id", "engagement_type", "graduation_year", "status", "alert_level", "risk_status", "integration_source", "source_entity_id", "tenant_id"),
        required=("record_id", "student_id", "engagement_type", "status", "alert_level", "risk_status"),
        fk_fields=(),
    ),
    "research_grants": EntityConfig(
        table="university_research_grants",
        fields=(
            "grant_code",
            "title",
            "pi_faculty_id",
            "deadline",
            "funding_amount",
            "status",
            "sponsor_notes",
            "tenant_id",
        ),
        required=("grant_code", "title", "pi_faculty_id", "deadline", "funding_amount", "status"),
        fk_fields=(),
    ),
    "research_grant_delay_alerts": EntityConfig(
        table="university_research_grant_delay_alerts",
        fields=(
            "grant_id",
            "grant_code",
            "pi_faculty_id",
            "status",
            "alert_status",
            "integration_source",
            "source_entity_id",
            "tenant_id",
        ),
        required=(
            "grant_id",
            "grant_code",
            "pi_faculty_id",
            "status",
            "alert_status",
            "integration_source",
            "source_entity_id",
        ),
        fk_fields=(),
    ),
    "research_publications": EntityConfig(
        table="university_research_publications",
        fields=(
            "publication_code",
            "title",
            "lead_author_id",
            "target_venue",
            "last_activity_days",
            "status",
            "tenant_id",
        ),
        required=("publication_code", "title", "lead_author_id", "target_venue", "last_activity_days", "status"),
        fk_fields=(),
    ),
    "publication_review_records": EntityConfig(
        table="university_publication_review_records",
        fields=(
            "publication_id",
            "publication_code",
            "lead_author_id",
            "target_venue",
            "status",
            "integration_source",
            "source_entity_id",
            "tenant_id",
        ),
        required=("publication_id", "publication_code", "lead_author_id", "status"),
        fk_fields=(),
    ),
    "research_labs": EntityConfig(
        table="university_research_labs",
        fields=("lab_code", "name", "status", "tenant_id"),
        required=("lab_code", "name", "status"),
        fk_fields=(),
    ),
    "research_ip_assets": EntityConfig(
        table="university_research_ip_assets",
        fields=("asset_code", "title", "status", "tenant_id"),
        required=("asset_code", "title", "status"),
        fk_fields=(),
    ),
    "research_experiments": EntityConfig(
        table="university_research_experiments",
        fields=("experiment_code", "title", "lab_code", "principal_investigator_id", "status", "tenant_id"),
        required=("experiment_code", "title", "lab_code", "principal_investigator_id", "status"),
        fk_fields=(),
    ),
    "faculty_performance_kpis": EntityConfig(
        table="university_faculty_performance_kpis",
        fields=("faculty_id", "name", "department_id", "kpi_period", "teaching_score", "research_score", "service_score", "overall_score", "status", "reviewer_id", "tenant_id"),
        required=("faculty_id", "name", "department_id", "kpi_period", "status"),
        fk_fields=(),
    ),
    "faculty_kpi_low_performance_alerts": EntityConfig(
        table="university_faculty_kpi_low_performance_alerts",
        fields=(
            "kpi_id",
            "faculty_id",
            "kpi_period",
            "overall_score",
            "alert_status",
            "integration_source",
            "source_entity_id",
            "tenant_id",
        ),
        required=("kpi_id", "faculty_id", "kpi_period", "overall_score", "alert_status", "integration_source", "source_entity_id"),
        fk_fields=(),
    ),
    "hr_employees": EntityConfig(
        table="university_hr_employees",
        fields=("employee_code", "full_name", "department_id", "role_title", "contract_type", "status", "tenant_id"),
        required=("employee_code", "full_name", "department_id", "role_title", "status"),
        fk_fields=(),
    ),
    "hr_offboarding_alerts": EntityConfig(
        table="university_hr_offboarding_alerts",
        fields=(
            "employee_id",
            "employee_code",
            "department_id",
            "offboarding_status",
            "alert_status",
            "integration_source",
            "source_entity_id",
            "tenant_id",
        ),
        required=("employee_id", "employee_code", "department_id", "offboarding_status", "alert_status", "integration_source", "source_entity_id"),
        fk_fields=(),
    ),
    "hr_payroll_cycles": EntityConfig(
        table="university_hr_payroll_cycles",
        fields=("cycle_code", "period_label", "total_gross", "total_net", "employee_count", "status", "tenant_id"),
        required=("cycle_code", "period_label", "status"),
        fk_fields=(),
    ),
    "hr_payroll_cycle_risk_alerts": EntityConfig(
        table="university_hr_payroll_cycle_risk_alerts",
        fields=(
            "cycle_id",
            "cycle_code",
            "period_label",
            "employee_count",
            "alert_status",
            "integration_source",
            "source_entity_id",
            "tenant_id",
        ),
        required=("cycle_id", "cycle_code", "alert_status", "integration_source", "source_entity_id"),
        fk_fields=(),
    ),
    "delinquency_records": EntityConfig(
        table="university_delinquency_records",
        fields=("student_id", "invoice_code", "amount_due", "days_overdue", "escalation_stage", "status", "tenant_id"),
        required=("student_id", "invoice_code", "amount_due", "days_overdue", "status"),
        fk_fields=(),
    ),
    "collections_agent_records": EntityConfig(
        table="university_collections_agent_records",
        fields=("record_id", "record_code", "student_id", "escalation_stage", "amount_due", "status", "integration_source", "source_entity_id", "tenant_id"),
        required=("record_id", "record_code", "student_id", "escalation_stage", "status"),
        fk_fields=(),
    ),
    # W67: delinquency legal escalation risk alerts
    "delinquency_legal_escalation_alerts": EntityConfig(
        table="university_delinquency_legal_escalation_alerts",
        fields=("record_id", "student_id", "escalation_stage", "amount_due", "alert_status", "integration_source", "source_entity_id", "tenant_id"),
        required=("record_id", "student_id", "alert_status", "integration_source", "source_entity_id"),
        fk_fields=(),
    ),
    "expense_policy_review_records": EntityConfig(
        table="finance_expense_policy_review_records",
        fields=("expense_id", "expense_code", "cost_center_id", "amount", "status", "integration_source", "source_entity_id", "tenant_id"),
        required=("expense_id", "status"),
        fk_fields=(),
    ),
    "expense_budget_exceeded_alerts": EntityConfig(
        table="finance_expense_budget_exceeded_alerts",
        fields=("expense_id", "cost_center_id", "category", "amount", "alert_status", "integration_source", "source_entity_id", "tenant_id"),
        required=("expense_id", "cost_center_id", "alert_status"),
        fk_fields=(),
    ),
    "facilities_sla_assignment_records": EntityConfig(
        table="university_facilities_sla_assignment_records",
        fields=("order_id", "order_code", "facility_code", "priority", "assigned_to", "status", "integration_source", "source_entity_id", "tenant_id"),
        required=("order_id", "order_code", "facility_code", "priority", "status"),
        fk_fields=(),
    ),
    "asset_writeoff_records": EntityConfig(
        table="university_asset_writeoff_records",
        fields=("asset_code", "depreciation_method", "original_value", "current_value", "status", "integration_source", "source_entity_id", "tenant_id"),
        required=("asset_code", "depreciation_method", "status"),
        fk_fields=(),
    ),
    "asset_condemned_risk_alerts": EntityConfig(
        table="university_asset_condemned_risk_alerts",
        fields=("asset_id", "asset_code", "category", "condition", "status", "alert_level", "risk_status", "integration_source", "source_entity_id", "tenant_id"),
        required=("asset_id", "asset_code", "category", "condition", "status", "alert_level", "risk_status"),
        fk_fields=(),
    ),
    "facilities_work_orders": EntityConfig(
        table="university_facilities_work_orders",
        fields=("order_code", "facility_code", "title", "work_type", "priority", "assigned_to", "status", "integration_source", "source_entity_id", "tenant_id"),
        required=("order_code", "facility_code", "title", "work_type", "priority", "status"),
        fk_fields=(),
    ),
    "facilities_maintenance_requests": EntityConfig(
        table="university_facilities_maintenance_requests",
        fields=("request_code", "facility_code", "issue_type", "severity", "notes", "status", "tenant_id"),
        required=("request_code", "facility_code", "issue_type", "severity", "status"),
        fk_fields=(),
    ),
    "facilities_overdue_work_order_alerts": EntityConfig(
        table="university_facilities_overdue_work_order_alerts",
        fields=(
            "order_id",
            "order_code",
            "facility_code",
            "priority",
            "status",
            "alert_level",
            "risk_status",
            "integration_source",
            "source_entity_id",
            "tenant_id",
        ),
        required=("order_id", "order_code", "facility_code", "priority", "status", "alert_level", "risk_status"),
        fk_fields=(),
    ),
    "asset_inventory_items": EntityConfig(
        table="university_asset_inventory_items",
        fields=("asset_code", "name", "category", "location", "condition", "purchase_year", "vendor", "status", "tenant_id"),
        required=("asset_code", "name", "category", "location", "condition", "purchase_year", "status"),
        fk_fields=(),
    ),
    "asset_depreciation_records": EntityConfig(
        table="university_asset_depreciation_records",
        fields=("asset_code", "depreciation_method", "original_value", "current_value", "depreciation_rate", "status", "tenant_id"),
        required=("asset_code", "depreciation_method", "original_value", "current_value", "depreciation_rate", "status"),
        fk_fields=(),
    ),
    "operations_facility_issues": EntityConfig(
        table="university_operations_facility_issues",
        fields=("facility_code", "issue_type", "severity", "status", "tenant_id"),
        required=("facility_code", "issue_type", "severity", "status"),
        fk_fields=(),
    ),
    "operations_work_orders": EntityConfig(
        table="university_operations_work_orders",
        fields=("work_order_code", "facility_code", "summary", "status", "tenant_id"),
        required=("work_order_code", "facility_code", "summary", "status"),
        fk_fields=(),
    ),
    "operations_dispatch_records": EntityConfig(
        table="university_operations_dispatch_records",
        fields=("work_order_id", "work_order_code", "facility_code", "assigned_team", "status", "integration_source", "source_entity_id", "tenant_id"),
        required=("work_order_id", "work_order_code", "facility_code", "assigned_team", "status"),
        fk_fields=(),
    ),
    "operations_cleaning_checks": EntityConfig(
        table="university_operations_cleaning_checks",
        fields=("room_code", "scheduled_slot", "status", "tenant_id"),
        required=("room_code", "scheduled_slot", "status"),
        fk_fields=(),
    ),
    "operations_room_readiness": EntityConfig(
        table="university_operations_room_readiness",
        fields=("room_code", "building_code", "status", "tenant_id"),
        required=("room_code", "building_code", "status"),
        fk_fields=(),
    ),
    "operations_maintenance_assets": EntityConfig(
        table="university_operations_maintenance_assets",
        fields=(
            "asset_code",
            "facility_code",
            "asset_type",
            "health_score",
            "days_since_maintenance",
            "expected_service_interval_days",
            "status",
            "tenant_id",
        ),
        required=(
            "asset_code",
            "facility_code",
            "asset_type",
            "health_score",
            "days_since_maintenance",
            "expected_service_interval_days",
            "status",
        ),
        fk_fields=(),
    ),
    "operations_utility_readings": EntityConfig(
        table="university_operations_utility_readings",
        fields=(
            "meter_code",
            "building_code",
            "utility_type",
            "usage_value",
            "baseline_value",
            "status",
            "tenant_id",
        ),
        required=(
            "meter_code",
            "building_code",
            "utility_type",
            "usage_value",
            "baseline_value",
            "status",
        ),
        fk_fields=(),
    ),
    "procurement_vendors": EntityConfig(
        table="university_procurement_vendors",
        fields=(
            "vendor_code",
            "name",
            "category",
            "sla_breach_rate",
            "on_time_delivery_rate",
            "status",
            "contact_name",
            "tenant_id",
        ),
        required=(
            "vendor_code",
            "name",
            "category",
            "sla_breach_rate",
            "on_time_delivery_rate",
            "status",
        ),
        fk_fields=(),
    ),
    "procurement_contracts": EntityConfig(
        table="university_procurement_contracts",
        fields=(
            "contract_code",
            "vendor_code",
            "title",
            "risk_score",
            "sla_target_met",
            "status",
            "tenant_id",
        ),
        required=("contract_code", "vendor_code", "title", "risk_score", "sla_target_met", "status"),
        fk_fields=(),
    ),
    "procurement_assets": EntityConfig(
        table="university_procurement_assets",
        fields=("asset_code", "title", "asset_category", "status", "tenant_id"),
        required=("asset_code", "title", "asset_category", "status"),
        fk_fields=(),
    ),
    "procurement_inventory_items": EntityConfig(
        table="university_procurement_inventory_items",
        fields=(
            "item_code",
            "title",
            "current_stock",
            "reorder_point",
            "daily_usage_rate",
            "lead_time_days",
            "auto_reorder_enabled",
            "status",
            "tenant_id",
        ),
        required=(
            "item_code",
            "title",
            "current_stock",
            "reorder_point",
            "daily_usage_rate",
            "lead_time_days",
            "auto_reorder_enabled",
            "status",
        ),
        fk_fields=(),
    ),
    "procurement_risk_alerts": EntityConfig(
        table="university_procurement_risk_alerts",
        fields=(
            "contract_id",
            "vendor_code",
            "risk_score",
            "alert_status",
            "integration_source",
            "source_entity_id",
            "tenant_id",
        ),
        required=("contract_id", "vendor_code", "risk_score", "alert_status", "integration_source", "source_entity_id"),
        fk_fields=(),
    ),
    "student_life_counseling_cases": EntityConfig(
        table="university_student_life_counseling_cases",
        fields=("case_code", "student_id", "concern_type", "status", "priority", "tenant_id"),
        required=("case_code", "student_id", "concern_type", "status"),
        fk_fields=(),
    ),
    "student_life_alert_records": EntityConfig(
        table="university_student_life_alert_records",
        fields=(
            "case_id",
            "case_code",
            "concern_type",
            "student_id",
            "integration_source",
            "source_entity_id",
            "tenant_id",
        ),
        required=("case_id",),
        fk_fields=(),
    ),
    "student_life_wellbeing_checkins": EntityConfig(
        table="university_student_life_wellbeing_checkins",
        fields=("student_id", "wellbeing_score", "status", "tenant_id"),
        required=("student_id", "wellbeing_score", "status"),
        fk_fields=(),
    ),
    "student_life_accessibility_supports": EntityConfig(
        table="university_student_life_accessibility_supports",
        fields=("support_code", "student_id", "support_type", "status", "tenant_id"),
        required=("support_code", "student_id", "support_type", "status"),
        fk_fields=(),
    ),
    "student_life_disciplinary_cases": EntityConfig(
        table="university_student_life_disciplinary_cases",
        fields=("incident_code", "student_id", "incident_type", "severity", "status", "tenant_id"),
        required=("incident_code", "student_id", "incident_type", "severity", "status"),
        fk_fields=(),
    ),
    "student_life_disciplinary_escalation_alerts": EntityConfig(
        table="university_student_life_disciplinary_escalation_alerts",
        fields=("case_id", "incident_code", "student_id", "incident_type", "severity", "status", "alert_level", "risk_status", "integration_source", "source_entity_id", "tenant_id"),
        required=("case_id", "incident_code", "student_id", "incident_type", "severity", "status", "alert_level", "risk_status"),
        fk_fields=(),
    ),
    # Phase IV: teaching quality analytics
    "teaching_quality_records": EntityConfig(
        table="university_teaching_quality_records",
        fields=("faculty_id", "course_id", "term_id", "quality_score", "kpi_score", "improvement_plan", "notes", "tenant_id"),
        required=("faculty_id", "course_id", "term_id", "quality_score", "kpi_score"),
        fk_fields=(),
    ),
    # Phase IV-IV2: proctoring / exam supervision
    "proctoring_records": EntityConfig(
        table="university_proctoring_records",
        fields=("exam_id", "faculty_id", "room_id", "violation_type", "severity", "student_id", "notes", "status", "tenant_id"),
        required=("exam_id", "faculty_id", "violation_type", "severity", "status"),
        fk_fields=(),
    ),
    # Phase IV-IV3: office hours scheduling
    "office_hours_records": EntityConfig(
        table="university_office_hours_records",
        fields=("faculty_id", "scheduled_at", "duration_minutes", "location", "status", "student_id", "notes", "no_show", "tenant_id"),
        required=("faculty_id", "scheduled_at", "duration_minutes", "status"),
        fk_fields=(),
    ),
    # Phase V-V1: budget planning
    "budget_plans": EntityConfig(
        table="finance_budget_plans",
        fields=("department_id", "fiscal_year", "total_amount", "currency", "status", "description", "notes_internal", "tenant_id"),
        required=("department_id", "fiscal_year", "total_amount", "status"),
        fk_fields=(),
    ),
    "budget_overrun_alerts": EntityConfig(
        table="finance_budget_overrun_alerts",
        fields=("plan_id", "alert_type", "integration_source", "source_entity_id", "tenant_id"),
        required=("plan_id", "alert_type"),
        fk_fields=(),
    ),
    "budget_allocations": EntityConfig(
        table="finance_budget_allocations",
        fields=("plan_id", "category", "allocated_amount", "spent_amount", "currency", "notes", "tenant_id"),
        required=("plan_id", "category", "allocated_amount"),
        fk_fields=(),
    ),
    "expense_records": EntityConfig(
        table="finance_expense_records",
        fields=("cost_center_id", "category", "amount", "currency", "status", "description", "payroll_ref", "tenant_id"),
        required=("cost_center_id", "category", "amount", "status"),
        fk_fields=(),
    ),
    "cost_centers": EntityConfig(
        table="finance_cost_centers",
        fields=("name", "code", "department_id", "budget_limit", "currency", "active", "tenant_id"),
        required=("name", "code", "budget_limit"),
        fk_fields=(),
    ),
    "security_incidents": EntityConfig(
        table="campus_security_incidents",
        fields=(
            "incident_code",
            "facility_code",
            "category",
            "severity",
            "status",
            "response_team",
            "reported_at",
            "description",
            "visitor_id",
            "access_control_event_id",
            "integration_source",
            "tenant_id",
        ),
        required=("incident_code", "facility_code", "category", "severity", "status"),
        fk_fields=(),
    ),
    "security_incident_escalation_records": EntityConfig(
        table="campus_security_incident_escalation_records",
        fields=(
            "incident_id",
            "incident_code",
            "facility_code",
            "category",
            "response_team",
            "escalation_level",
            "status",
            "integration_source",
            "source_entity_id",
            "tenant_id",
        ),
        required=(
            "incident_id",
            "incident_code",
            "facility_code",
            "category",
            "response_team",
            "escalation_level",
            "status",
        ),
        fk_fields=(),
    ),
    "security_visitors": EntityConfig(
        table="campus_security_visitors",
        fields=(
            "visitor_name",
            "host_faculty_id",
            "visit_purpose",
            "status",
            "access_status",
            "badge_id",
            "check_in_at",
            "check_out_at",
            "access_control_event_id",
            "tenant_id",
        ),
        required=("visitor_name", "visit_purpose", "status", "access_status"),
        fk_fields=(),
    ),
    "transport_routes": EntityConfig(
        table="campus_transport_routes",
        fields=(
            "route_code",
            "route_name",
            "status",
            "vehicle_type",
            "departure_time",
            "arrival_time",
            "capacity",
            "assigned_driver",
            "tenant_id",
        ),
        required=("route_code", "route_name", "status"),
        fk_fields=(),
    ),
    "transport_bookings": EntityConfig(
        table="campus_transport_bookings",
        fields=(
            "route_code",
            "student_id",
            "booking_status",
            "seat_number",
            "journey_date",
            "tenant_id",
        ),
        required=("route_code", "student_id", "booking_status"),
        fk_fields=(),
    ),
    "dining_menus": EntityConfig(
        table="campus_dining_menus",
        fields=(
            "menu_code",
            "facility_code",
            "meal_type",
            "date",
            "status",
            "serving_window",
            "capacity",
            "available_capacity",
            "tenant_id",
        ),
        required=("menu_code", "facility_code", "meal_type", "status"),
        fk_fields=(),
    ),
    "dining_capacity_alert_records": EntityConfig(
        table="campus_dining_capacity_alert_records",
        fields=(
            "menu_id",
            "menu_code",
            "facility_code",
            "meal_type",
            "alert_level",
            "status",
            "integration_source",
            "source_entity_id",
            "tenant_id",
        ),
        required=(
            "menu_id",
            "menu_code",
            "facility_code",
            "meal_type",
            "alert_level",
            "status",
        ),
        fk_fields=(),
    ),
    "transport_disruption_records": EntityConfig(
        table="campus_transport_disruption_records",
        fields=(
            "route_id",
            "route_code",
            "vehicle_type",
            "disruption_status",
            "severity",
            "record_status",
            "integration_source",
            "source_entity_id",
            "tenant_id",
        ),
        required=(
            "route_id",
            "route_code",
            "disruption_status",
            "severity",
            "record_status",
        ),
        fk_fields=(),
    ),
    "dining_orders": EntityConfig(
        table="campus_dining_orders",
        fields=(
            "order_code",
            "menu_code",
            "facility_code",
            "meal_type",
            "status",
            "student_id",
            "special_request",
            "tenant_id",
        ),
        required=("order_code", "menu_code", "facility_code", "meal_type", "status"),
        fk_fields=(),
    ),
    "campus_sla_records": EntityConfig(
        table="campus_sla_records",
        fields=(
            "service_type",
            "facility_code",
            "target_sla_minutes",
            "actual_minutes",
            "status",
            "priority",
            "reported_at",
            "resolved_at",
            "description",
            "integration_source",
            "tenant_id",
        ),
        required=("service_type", "facility_code", "target_sla_minutes", "status"),
        fk_fields=(),
    ),
    "campus_sla_breach_risk_alerts": EntityConfig(
        table="university_campus_sla_breach_risk_alerts",
        fields=("record_id", "service_type", "facility_code", "priority", "status", "alert_level", "risk_status", "integration_source", "source_entity_id", "tenant_id"),
        required=("record_id", "service_type", "facility_code", "status", "alert_level", "risk_status"),
        fk_fields=(),
    ),
    "ethics_reviews": EntityConfig(
        table="research_ethics_reviews",
        fields=(
            "review_code",
            "project_title",
            "principal_investigator_id",
            "review_type",
            "status",
            "submission_date",
            "decision_date",
            "risk_level",
            "notes",
            "integration_source",
            "committee_name",
            "tenant_id",
        ),
        required=("review_code", "project_title", "principal_investigator_id", "status"),
        fk_fields=(),
    ),
    "ethics_alert_records": EntityConfig(
        table="research_ethics_alert_records",
        fields=(
            "review_id",
            "review_code",
            "risk_level",
            "integration_source",
            "source_entity_id",
            "tenant_id",
        ),
        required=("review_id",),
        fk_fields=(),
    ),
    "ip_assets": EntityConfig(
        table="ip_management_assets",
        fields=(
            "asset_code",
            "title",
            "inventor_ids",
            "ip_type",
            "status",
            "filing_date",
            "grant_date",
            "commercialization_status",
            "licensing_revenue",
            "notes",
            "integration_source",
            "department",
            "tenant_id",
        ),
        required=("asset_code", "title", "ip_type", "status"),
        fk_fields=(),
    ),
    "ip_licensing_records": EntityConfig(
        table="ip_management_licensing_records",
        fields=(
            "asset_id",
            "asset_code",
            "commercialization_status",
            "integration_source",
            "source_entity_id",
            "tenant_id",
        ),
        required=("asset_id",),
        fk_fields=(),
    ),
    "integrity_case": EntityConfig(
        table="university_academic_integrity_cases",
        fields=(
            "student_id",
            "course_id",
            "assignment_id",
            "case_type",
            "description",
            "evidence_url",
            "priority",
            "status",
            "resolution_notes",
            "recommended_action",
            "reviewer_notes",
            "created_by",
            "tenant_id",
        ),
        required=("student_id", "course_id", "case_type", "description", "priority", "status"),
        fk_fields=(),
    ),
    "integrity_escalation_alerts": EntityConfig(
        table="university_academic_integrity_escalation_alerts",
        fields=(
            "case_id",
            "alert_status",
            "integration_source",
            "source_entity_id",
            "tenant_id",
        ),
        required=("case_id", "alert_status", "integration_source", "source_entity_id"),
        fk_fields=(),
    ),
    "equipment_items": EntityConfig(
        table="research_equipment_items",
        fields=(
            "equipment_code",
            "name",
            "category",
            "location",
            "status",
            "capacity",
            "notes",
            "integration_source",
            "tenant_id",
        ),
        required=("equipment_code", "name", "category", "status"),
        fk_fields=(),
    ),
    "equipment_bookings": EntityConfig(
        table="research_equipment_bookings",
        fields=(
            "equipment_code",
            "requester_id",
            "start_time",
            "end_time",
            "booking_status",
            "purpose",
            "conflict_flag",
            "cancellation_reason",
            "integration_source",
            "tenant_id",
        ),
        required=("equipment_code", "requester_id", "start_time", "end_time", "booking_status"),
        fk_fields=(),
    ),
    "scholarship_applications": EntityConfig(
        table="scholarship_applications",
        fields=(
            "application_code",
            "student_id",
            "scholarship_type",
            "status",
            "gpa",
            "requested_amount",
            "notes",
            "integration_source",
            "tenant_id",
        ),
        required=("application_code", "student_id", "scholarship_type", "status", "gpa", "requested_amount"),
        fk_fields=(),
    ),
    "scholarship_awards": EntityConfig(
        table="scholarship_awards",
        fields=(
            "award_code",
            "student_id",
            "scholarship_type",
            "status",
            "amount",
            "renewal_deadline",
            "gpa_threshold",
            "current_gpa",
            "notes",
            "integration_source",
            "tenant_id",
        ),
        required=("award_code", "student_id", "scholarship_type", "status", "amount", "current_gpa"),
        fk_fields=(),
    ),
    "scholarship_revocation_alerts": EntityConfig(
        table="university_scholarship_revocation_alerts",
        fields=(
            "award_id",
            "alert_status",
            "integration_source",
            "source_entity_id",
            "tenant_id",
        ),
        required=("award_id", "alert_status", "integration_source", "source_entity_id"),
        fk_fields=(),
    ),
    "equipment_booking_overdue_alerts": EntityConfig(
        table="university_equipment_booking_overdue_alerts",
        fields=(
            "booking_id",
            "alert_status",
            "integration_source",
            "source_entity_id",
            "tenant_id",
        ),
        required=("booking_id", "alert_status", "integration_source", "source_entity_id"),
        fk_fields=(),
    ),
    "communication_messages": EntityConfig(
        table="communication_messages",
        fields=(
            "message_code",
            "title",
            "message_type",
            "target_audience",
            "status",
            "recipients_count",
            "delivered_count",
            "opened_count",
            "integration_source",
            "channel",
            "tenant_id",
        ),
        required=("message_code", "title", "message_type", "target_audience", "status", "recipients_count"),
        fk_fields=(),
    ),
    "communication_broadcast_audits": EntityConfig(
        table="university_communication_broadcast_audits",
        fields=(
            "message_id",
            "message_code",
            "message_type",
            "recipients_count",
            "audit_status",
            "integration_source",
            "source_entity_id",
            "tenant_id",
        ),
        required=("message_id", "message_code", "message_type", "recipients_count", "audit_status", "integration_source", "source_entity_id"),
        fk_fields=(),
    ),
    "communication_broadcast_risk_alerts": EntityConfig(
        table="university_communication_broadcast_risk_alerts",
        fields=("message_id", "message_code", "message_type", "recipients_count", "status", "alert_level", "risk_status", "integration_source", "source_entity_id", "tenant_id"),
        required=("message_id", "message_code", "message_type", "status", "alert_level", "risk_status"),
        fk_fields=(),
    ),
    "accreditation_records": EntityConfig(
        table="accreditation_records",
        fields=(
            "standard_code",
            "standard_type",
            "title",
            "owner_department",
            "review_cycle_year",
            "due_date",
            "evidence_summary",
            "risk_level",
            "external_auditor_id",
            "status",
            "reviewer_notes",
            "remediation_plan",
            "tenant_id",
        ),
        required=(
            "standard_code",
            "standard_type",
            "title",
            "owner_department",
            "review_cycle_year",
            "risk_level",
            "status",
        ),
        fk_fields=(),
    ),
    "accreditation_risk_alerts": EntityConfig(
        table="university_accreditation_risk_alerts",
        fields=(
            "accreditation_id",
            "standard_code",
            "standard_type",
            "owner_department",
            "risk_level",
            "alert_status",
            "integration_source",
            "source_entity_id",
            "tenant_id",
        ),
        required=("accreditation_id", "standard_code", "standard_type", "owner_department", "risk_level", "alert_status", "integration_source", "source_entity_id"),
        fk_fields=(),
    ),
    "thesis_records": EntityConfig(
        table="thesis_records",
        fields=(
            "thesis_code",
            "student_id",
            "title",
            "advisor_faculty_id",
            "status",
            "defense_date",
            "repository_url",
            "keywords",
            "tenant_id",
        ),
        required=("thesis_code", "student_id", "title", "status"),
        fk_fields=(),
    ),
    "thesis_overdue_alerts": EntityConfig(
        table="university_thesis_overdue_alerts",
        fields=(
            "thesis_id",
            "thesis_code",
            "student_id",
            "current_status",
            "alert_status",
            "integration_source",
            "source_entity_id",
            "tenant_id",
        ),
        required=("thesis_id", "thesis_code", "student_id", "current_status", "alert_status", "integration_source", "source_entity_id"),
        fk_fields=(),
    ),
    "thesis_rejection_risk_alerts": EntityConfig(
        table="university_thesis_rejection_risk_alerts",
        fields=(
            "thesis_id",
            "thesis_code",
            "student_id",
            "current_status",
            "alert_status",
            "integration_source",
            "source_entity_id",
            "tenant_id",
        ),
        required=("thesis_id", "thesis_code", "student_id", "current_status", "alert_status", "integration_source", "source_entity_id"),
        fk_fields=(),
    ),
    # Syllabus Governance — orphan frontend page backend
    "syllabi": EntityConfig(
        table="app_syllabi",
        fields=(
            "course_code",
            "course_title",
            "department_id",
            "faculty_id",
            "term_id",
            "status",
            "credit_hours",
            "tenant_id",
        ),
        required=("course_code", "course_title", "department_id", "faculty_id", "term_id", "status"),
        fk_fields=(),
    ),
    "syllabus_review_backlogs": EntityConfig(
        table="university_syllabus_review_backlogs",
        fields=(
            "syllabus_id",
            "course_code",
            "department_id",
            "backlog_status",
            "integration_source",
            "source_entity_id",
            "tenant_id",
        ),
        required=("syllabus_id", "course_code", "department_id", "backlog_status", "integration_source", "source_entity_id"),
        fk_fields=(),
    ),
    # Exam Governance — orphan frontend page backend
    "exams": EntityConfig(
        table="app_exams",
        fields=(
            "course_code",
            "course_title",
            "faculty_id",
            "exam_type",
            "term_id",
            "status",
            "scheduled_date",
            "scheduled_time",
            "duration_minutes",
            "is_proctored",
            "proctoring_mode",
            "location_room",
            "tenant_id",
        ),
        required=("course_code", "course_title", "faculty_id", "exam_type", "term_id", "status"),
        fk_fields=(),
    ),
    "exam_proctoring_alerts": EntityConfig(
        table="university_exam_proctoring_alerts",
        fields=(
            "exam_id",
            "course_code",
            "proctoring_mode",
            "alert_status",
            "integration_source",
            "source_entity_id",
            "tenant_id",
        ),
        required=("exam_id", "course_code", "proctoring_mode", "alert_status", "integration_source", "source_entity_id"),
        fk_fields=(),
    ),
    # Phase XII-XII4: Model Evaluation
    "model_eval_runs": EntityConfig(
        table="university_model_eval_runs",
        fields=(
            "run_id",
            "model_name",
            "eval_set_name",
            "metric_names",
            "status",
            "metrics",
            "notes",
            "created_by",
            "created_at",
            "completed_at",
            "tenant_id",
        ),
        required=("run_id", "model_name", "eval_set_name", "status", "created_by"),
        fk_fields=(),
    ),
    # Phase XII-XII3: Prompt Management
    "prompt_templates": EntityConfig(
        table="university_prompt_templates",
        fields=(
            "template_id",
            "name",
            "description",
            "template_text",
            "variables",
            "category",
            "version",
            "is_active",
            "created_by",
            "created_at",
            "tenant_id",
        ),
        required=("template_id", "name", "template_text", "created_by"),
        fk_fields=(),
    ),
}


@dataclass
class UniversityMemoryState:
    data: dict[str, dict[int, dict[str, object]]] = field(default_factory=dict)
    counters: dict[str, int] = field(default_factory=dict)


_state_lock = Lock()
_state = UniversityMemoryState(
    data={name: {} for name in ENTITY_CONFIGS},
    counters={name: 0 for name in ENTITY_CONFIGS},
)


def clear_university_state() -> None:
    with _state_lock:
        for name in ENTITY_CONFIGS:
            _state.data[name].clear()
            _state.counters[name] = 0


__all__ = [
    "EntityConfig",
    "ENTITY_CONFIGS",
    "UniversityMemoryState",
    "_state",
    "_state_lock",
    "clear_university_state",
    "get_raw_conn",
    "psycopg",
]
