from __future__ import annotations

from dataclasses import dataclass, field
from threading import Lock

from app.core.db import get_raw_conn

try:
    import psycopg
except ImportError:  # pragma: no cover
    psycopg = None


@dataclass(frozen=True)
class EntityConfig:
    table: str
    fields: tuple[str, ...]
    required: tuple[str, ...]
    fk_fields: tuple[str, ...] = ()


ENTITY_CONFIGS: dict[str, EntityConfig] = {
    "students": EntityConfig(
        table="university_students",
        fields=("student_id", "first_name", "last_name", "email", "status", "tenant_id"),
        required=("student_id", "first_name", "last_name", "email", "status"),
    ),
    "faculty": EntityConfig(
        table="university_faculty",
        fields=("faculty_id", "first_name", "last_name", "department", "email", "status", "tenant_id"),
        required=("faculty_id", "first_name", "last_name", "department", "email", "status"),
    ),
    "faculty_contracts": EntityConfig(
        table="university_faculty_contracts",
        fields=(
            "faculty_id",
            "contract_type",
            "start_date",
            "end_date",
            "fte_ratio",
            "max_credit_hours",
            "status",
            "notes",
            "tenant_id",
        ),
        required=(
            "faculty_id",
            "contract_type",
            "start_date",
            "fte_ratio",
            "max_credit_hours",
            "status",
        ),
        fk_fields=(),
    ),
    "programs": EntityConfig(
        table="university_programs",
        fields=("program_code", "title", "degree_type", "faculty", "status", "tenant_id"),
        required=("program_code", "title", "degree_type", "faculty", "status"),
    ),
    "courses": EntityConfig(
        table="university_courses",
        fields=("course_code", "title", "credits", "program_id", "status", "tenant_id"),
        required=("course_code", "title", "credits", "program_id", "status"),
        fk_fields=("program_id",),
    ),
    "enrollments": EntityConfig(
        table="university_enrollments",
        fields=("student_id", "course_id", "semester", "status", "tenant_id"),
        required=("student_id", "course_id", "semester", "status"),
        fk_fields=("student_id", "course_id"),
    ),
    "academic_records": EntityConfig(
        table="university_academic_records",
        fields=("student_id", "course_id", "grade", "semester", "status", "tenant_id"),
        required=("student_id", "course_id", "grade", "semester", "status"),
        fk_fields=("student_id", "course_id"),
    ),
    "advising_sessions": EntityConfig(
        table="university_advising_sessions",
        fields=(
            "student_id",
            "advisor_id",
            "session_type",
            "status",
            "scheduled_at",
            "notes",
            "outcome",
            "tenant_id",
        ),
        required=("student_id", "advisor_id", "session_type", "status"),
        fk_fields=(),
    ),
    "student_service_tickets": EntityConfig(
        table="university_student_service_tickets",
        fields=(
            "student_id",
            "category",
            "subject",
            "description",
            "priority",
            "status",
            "owner_id",
            "channel",
            "resolution_notes",
            "tenant_id",
        ),
        required=("student_id", "category", "subject", "description", "priority", "status"),
        fk_fields=(),
    ),
    "career_opportunities": EntityConfig(
        table="university_career_opportunities",
        fields=(
            "student_id",
            "title",
            "company",
            "opportunity_type",
            "status",
            "owner_id",
            "start_date",
            "notes",
            "tenant_id",
        ),
        required=("student_id", "title", "company", "opportunity_type", "status"),
        fk_fields=(),
    ),
    "financial_aid_records": EntityConfig(
        table="university_financial_aid_records",
        fields=(
            "student_id",
            "aid_type",
            "amount",
            "currency",
            "status",
            "term",
            "reviewer_id",
            "notes",
            "tenant_id",
        ),
        required=("student_id", "aid_type", "amount", "currency", "status", "term"),
        fk_fields=(),
    ),
    "housing_requests": EntityConfig(
        table="university_housing_requests",
        fields=(
            "student_id",
            "request_type",
            "dormitory",
            "room_preference",
            "status",
            "manager_id",
            "notes",
            "tenant_id",
        ),
        required=("student_id", "request_type", "dormitory", "status"),
        fk_fields=(),
    ),
    "alumni_records": EntityConfig(
        table="university_alumni_records",
        fields=(
            "student_id",
            "graduation_year",
            "status",
            "engagement_type",
            "employer",
            "contact_email",
            "notes",
            "tenant_id",
        ),
        required=("student_id", "graduation_year", "status", "engagement_type"),
        fk_fields=(),
    ),
    "research_grants": EntityConfig(
        table="university_research_grants",
        fields=(
            "grant_code",
            "title",
            "pi_faculty_id",
            "deadline",
            "funding_amount",
            "status",
            "tenant_id",
        ),
        required=("grant_code", "title", "pi_faculty_id", "deadline", "funding_amount", "status"),
        fk_fields=(),
    ),
    "research_publications": EntityConfig(
        table="university_research_publications",
        fields=(
            "publication_code",
            "title",
            "lead_author_id",
            "target_venue",
            "last_activity_days",
            "status",
            "tenant_id",
        ),
        required=("publication_code", "title", "lead_author_id", "target_venue", "last_activity_days", "status"),
        fk_fields=(),
    ),
    "research_labs": EntityConfig(
        table="university_research_labs",
        fields=("lab_code", "name", "status", "tenant_id"),
        required=("lab_code", "name", "status"),
        fk_fields=(),
    ),
    "research_ip_assets": EntityConfig(
        table="university_research_ip_assets",
        fields=("asset_code", "title", "status", "tenant_id"),
        required=("asset_code", "title", "status"),
        fk_fields=(),
    ),
    "research_experiments": EntityConfig(
        table="university_research_experiments",
        fields=("experiment_code", "title", "lab_code", "principal_investigator_id", "status", "tenant_id"),
        required=("experiment_code", "title", "lab_code", "principal_investigator_id", "status"),
        fk_fields=(),
    ),
    "faculty_performance_kpis": EntityConfig(
        table="university_faculty_performance_kpis",
        fields=("faculty_id", "name", "department_id", "kpi_period", "teaching_score", "research_score", "service_score", "overall_score", "status", "tenant_id"),
        required=("faculty_id", "name", "department_id", "kpi_period", "status"),
        fk_fields=(),
    ),
    "hr_employees": EntityConfig(
        table="university_hr_employees",
        fields=("employee_code", "full_name", "department_id", "role_title", "status", "tenant_id"),
        required=("employee_code", "full_name", "department_id", "role_title", "status"),
        fk_fields=(),
    ),
    "hr_payroll_cycles": EntityConfig(
        table="university_hr_payroll_cycles",
        fields=("cycle_code", "period_label", "total_gross", "total_net", "employee_count", "status", "tenant_id"),
        required=("cycle_code", "period_label", "status"),
        fk_fields=(),
    ),
    "delinquency_records": EntityConfig(
        table="university_delinquency_records",
        fields=("student_id", "invoice_code", "amount_due", "days_overdue", "escalation_stage", "status", "tenant_id"),
        required=("student_id", "invoice_code", "amount_due", "days_overdue", "status"),
        fk_fields=(),
    ),
    "facilities_work_orders": EntityConfig(
        table="university_facilities_work_orders",
        fields=("order_code", "facility_code", "title", "work_type", "priority", "assigned_to", "status", "tenant_id"),
        required=("order_code", "facility_code", "title", "work_type", "priority", "status"),
        fk_fields=(),
    ),
    "facilities_maintenance_requests": EntityConfig(
        table="university_facilities_maintenance_requests",
        fields=("request_code", "facility_code", "issue_type", "severity", "notes", "status", "tenant_id"),
        required=("request_code", "facility_code", "issue_type", "severity", "status"),
        fk_fields=(),
    ),
    "asset_inventory_items": EntityConfig(
        table="university_asset_inventory_items",
        fields=("asset_code", "name", "category", "location", "condition", "purchase_year", "vendor", "status", "tenant_id"),
        required=("asset_code", "name", "category", "location", "condition", "purchase_year", "status"),
        fk_fields=(),
    ),
    "asset_depreciation_records": EntityConfig(
        table="university_asset_depreciation_records",
        fields=("asset_code", "depreciation_method", "original_value", "current_value", "depreciation_rate", "status", "tenant_id"),
        required=("asset_code", "depreciation_method", "original_value", "current_value", "depreciation_rate", "status"),
        fk_fields=(),
    ),
    "operations_facility_issues": EntityConfig(
        table="university_operations_facility_issues",
        fields=("facility_code", "issue_type", "severity", "status", "tenant_id"),
        required=("facility_code", "issue_type", "severity", "status"),
        fk_fields=(),
    ),
    "operations_work_orders": EntityConfig(
        table="university_operations_work_orders",
        fields=("work_order_code", "facility_code", "summary", "status", "tenant_id"),
        required=("work_order_code", "facility_code", "summary", "status"),
        fk_fields=(),
    ),
    "operations_cleaning_checks": EntityConfig(
        table="university_operations_cleaning_checks",
        fields=("room_code", "scheduled_slot", "status", "tenant_id"),
        required=("room_code", "scheduled_slot", "status"),
        fk_fields=(),
    ),
    "operations_room_readiness": EntityConfig(
        table="university_operations_room_readiness",
        fields=("room_code", "building_code", "status", "tenant_id"),
        required=("room_code", "building_code", "status"),
        fk_fields=(),
    ),
    "operations_maintenance_assets": EntityConfig(
        table="university_operations_maintenance_assets",
        fields=(
            "asset_code",
            "facility_code",
            "asset_type",
            "health_score",
            "days_since_maintenance",
            "expected_service_interval_days",
            "status",
            "tenant_id",
        ),
        required=(
            "asset_code",
            "facility_code",
            "asset_type",
            "health_score",
            "days_since_maintenance",
            "expected_service_interval_days",
            "status",
        ),
        fk_fields=(),
    ),
    "operations_utility_readings": EntityConfig(
        table="university_operations_utility_readings",
        fields=(
            "meter_code",
            "building_code",
            "utility_type",
            "usage_value",
            "baseline_value",
            "status",
            "tenant_id",
        ),
        required=(
            "meter_code",
            "building_code",
            "utility_type",
            "usage_value",
            "baseline_value",
            "status",
        ),
        fk_fields=(),
    ),
    "procurement_vendors": EntityConfig(
        table="university_procurement_vendors",
        fields=(
            "vendor_code",
            "name",
            "category",
            "sla_breach_rate",
            "on_time_delivery_rate",
            "status",
            "tenant_id",
        ),
        required=(
            "vendor_code",
            "name",
            "category",
            "sla_breach_rate",
            "on_time_delivery_rate",
            "status",
        ),
        fk_fields=(),
    ),
    "procurement_contracts": EntityConfig(
        table="university_procurement_contracts",
        fields=(
            "contract_code",
            "vendor_code",
            "title",
            "risk_score",
            "sla_target_met",
            "status",
            "tenant_id",
        ),
        required=("contract_code", "vendor_code", "title", "risk_score", "sla_target_met", "status"),
        fk_fields=(),
    ),
    "procurement_assets": EntityConfig(
        table="university_procurement_assets",
        fields=("asset_code", "title", "asset_category", "status", "tenant_id"),
        required=("asset_code", "title", "asset_category", "status"),
        fk_fields=(),
    ),
    "procurement_inventory_items": EntityConfig(
        table="university_procurement_inventory_items",
        fields=(
            "item_code",
            "title",
            "current_stock",
            "reorder_point",
            "daily_usage_rate",
            "lead_time_days",
            "auto_reorder_enabled",
            "status",
            "tenant_id",
        ),
        required=(
            "item_code",
            "title",
            "current_stock",
            "reorder_point",
            "daily_usage_rate",
            "lead_time_days",
            "auto_reorder_enabled",
            "status",
        ),
        fk_fields=(),
    ),
    "student_life_counseling_cases": EntityConfig(
        table="university_student_life_counseling_cases",
        fields=("case_code", "student_id", "concern_type", "status", "tenant_id"),
        required=("case_code", "student_id", "concern_type", "status"),
        fk_fields=(),
    ),
    "student_life_wellbeing_checkins": EntityConfig(
        table="university_student_life_wellbeing_checkins",
        fields=("student_id", "wellbeing_score", "status", "tenant_id"),
        required=("student_id", "wellbeing_score", "status"),
        fk_fields=(),
    ),
    "student_life_accessibility_supports": EntityConfig(
        table="university_student_life_accessibility_supports",
        fields=("support_code", "student_id", "support_type", "status", "tenant_id"),
        required=("support_code", "student_id", "support_type", "status"),
        fk_fields=(),
    ),
    "student_life_disciplinary_cases": EntityConfig(
        table="university_student_life_disciplinary_cases",
        fields=("incident_code", "student_id", "incident_type", "severity", "status", "tenant_id"),
        required=("incident_code", "student_id", "incident_type", "severity", "status"),
        fk_fields=(),
    ),
    # Phase IV: teaching quality analytics
    "teaching_quality_records": EntityConfig(
        table="university_teaching_quality_records",
        fields=("faculty_id", "course_id", "term_id", "quality_score", "kpi_score", "improvement_plan", "notes", "tenant_id"),
        required=("faculty_id", "course_id", "term_id", "quality_score", "kpi_score"),
        fk_fields=(),
    ),
    # Phase IV-IV2: proctoring / exam supervision
    "proctoring_records": EntityConfig(
        table="university_proctoring_records",
        fields=("exam_id", "faculty_id", "room_id", "violation_type", "severity", "student_id", "notes", "status", "tenant_id"),
        required=("exam_id", "faculty_id", "violation_type", "severity", "status"),
        fk_fields=(),
    ),
    # Phase IV-IV3: office hours scheduling
    "office_hours_records": EntityConfig(
        table="university_office_hours_records",
        fields=("faculty_id", "scheduled_at", "duration_minutes", "location", "status", "student_id", "notes", "no_show", "tenant_id"),
        required=("faculty_id", "scheduled_at", "duration_minutes", "status"),
        fk_fields=(),
    ),
    # Phase V-V1: budget planning
    "budget_plans": EntityConfig(
        table="finance_budget_plans",
        fields=("department_id", "fiscal_year", "total_amount", "currency", "status", "description", "tenant_id"),
        required=("department_id", "fiscal_year", "total_amount", "status"),
        fk_fields=(),
    ),
    "budget_allocations": EntityConfig(
        table="finance_budget_allocations",
        fields=("plan_id", "category", "allocated_amount", "spent_amount", "currency", "notes", "tenant_id"),
        required=("plan_id", "category", "allocated_amount"),
        fk_fields=(),
    ),
    "expense_records": EntityConfig(
        table="finance_expense_records",
        fields=("cost_center_id", "category", "amount", "currency", "status", "description", "payroll_ref", "tenant_id"),
        required=("cost_center_id", "category", "amount", "status"),
        fk_fields=(),
    ),
    "cost_centers": EntityConfig(
        table="finance_cost_centers",
        fields=("name", "code", "department_id", "budget_limit", "currency", "active", "tenant_id"),
        required=("name", "code", "budget_limit"),
        fk_fields=(),
    ),
    "security_incidents": EntityConfig(
        table="campus_security_incidents",
        fields=(
            "incident_code",
            "facility_code",
            "category",
            "severity",
            "status",
            "reported_at",
            "description",
            "visitor_id",
            "access_control_event_id",
            "integration_source",
            "tenant_id",
        ),
        required=("incident_code", "facility_code", "category", "severity", "status"),
        fk_fields=(),
    ),
    "security_visitors": EntityConfig(
        table="campus_security_visitors",
        fields=(
            "visitor_name",
            "host_faculty_id",
            "visit_purpose",
            "status",
            "access_status",
            "badge_id",
            "check_in_at",
            "check_out_at",
            "access_control_event_id",
            "tenant_id",
        ),
        required=("visitor_name", "visit_purpose", "status", "access_status"),
        fk_fields=(),
    ),
    "transport_routes": EntityConfig(
        table="campus_transport_routes",
        fields=(
            "route_code",
            "route_name",
            "status",
            "vehicle_type",
            "departure_time",
            "arrival_time",
            "capacity",
            "assigned_driver",
            "tenant_id",
        ),
        required=("route_code", "route_name", "status"),
        fk_fields=(),
    ),
    "transport_bookings": EntityConfig(
        table="campus_transport_bookings",
        fields=(
            "route_code",
            "student_id",
            "booking_status",
            "seat_number",
            "journey_date",
            "tenant_id",
        ),
        required=("route_code", "student_id", "booking_status"),
        fk_fields=(),
    ),
    "dining_menus": EntityConfig(
        table="campus_dining_menus",
        fields=(
            "menu_code",
            "facility_code",
            "meal_type",
            "date",
            "status",
            "capacity",
            "available_capacity",
            "tenant_id",
        ),
        required=("menu_code", "facility_code", "meal_type", "status"),
        fk_fields=(),
    ),
    "dining_orders": EntityConfig(
        table="campus_dining_orders",
        fields=(
            "order_code",
            "menu_code",
            "facility_code",
            "meal_type",
            "status",
            "student_id",
            "special_request",
            "tenant_id",
        ),
        required=("order_code", "menu_code", "facility_code", "meal_type", "status"),
        fk_fields=(),
    ),
    "campus_sla_records": EntityConfig(
        table="campus_sla_records",
        fields=(
            "service_type",
            "facility_code",
            "target_sla_minutes",
            "actual_minutes",
            "status",
            "reported_at",
            "resolved_at",
            "description",
            "integration_source",
            "tenant_id",
        ),
        required=("service_type", "facility_code", "target_sla_minutes", "status"),
        fk_fields=(),
    ),
    "ethics_reviews": EntityConfig(
        table="research_ethics_reviews",
        fields=(
            "review_code",
            "project_title",
            "principal_investigator_id",
            "review_type",
            "status",
            "submission_date",
            "decision_date",
            "risk_level",
            "notes",
            "integration_source",
            "tenant_id",
        ),
        required=("review_code", "project_title", "principal_investigator_id", "status"),
        fk_fields=(),
    ),
    "ip_assets": EntityConfig(
        table="ip_management_assets",
        fields=(
            "asset_code",
            "title",
            "inventor_ids",
            "ip_type",
            "status",
            "filing_date",
            "grant_date",
            "commercialization_status",
            "licensing_revenue",
            "notes",
            "integration_source",
            "tenant_id",
        ),
        required=("asset_code", "title", "ip_type", "status"),
        fk_fields=(),
    ),
    "equipment_items": EntityConfig(
        table="research_equipment_items",
        fields=(
            "equipment_code",
            "name",
            "category",
            "location",
            "status",
            "capacity",
            "notes",
            "integration_source",
            "tenant_id",
        ),
        required=("equipment_code", "name", "category", "status"),
        fk_fields=(),
    ),
    "equipment_bookings": EntityConfig(
        table="research_equipment_bookings",
        fields=(
            "equipment_code",
            "requester_id",
            "start_time",
            "end_time",
            "booking_status",
            "purpose",
            "conflict_flag",
            "integration_source",
            "tenant_id",
        ),
        required=("equipment_code", "requester_id", "start_time", "end_time", "booking_status"),
        fk_fields=(),
    ),
    "scholarship_applications": EntityConfig(
        table="scholarship_applications",
        fields=(
            "application_code",
            "student_id",
            "scholarship_type",
            "status",
            "gpa",
            "requested_amount",
            "notes",
            "integration_source",
            "tenant_id",
        ),
        required=("application_code", "student_id", "scholarship_type", "status", "gpa", "requested_amount"),
        fk_fields=(),
    ),
    "scholarship_awards": EntityConfig(
        table="scholarship_awards",
        fields=(
            "award_code",
            "student_id",
            "scholarship_type",
            "status",
            "amount",
            "renewal_deadline",
            "gpa_threshold",
            "current_gpa",
            "notes",
            "integration_source",
            "tenant_id",
        ),
        required=("award_code", "student_id", "scholarship_type", "status", "amount", "current_gpa"),
        fk_fields=(),
    ),
    "communication_messages": EntityConfig(
        table="communication_messages",
        fields=(
            "message_code",
            "title",
            "message_type",
            "target_audience",
            "status",
            "recipients_count",
            "delivered_count",
            "opened_count",
            "integration_source",
            "tenant_id",
        ),
        required=("message_code", "title", "message_type", "target_audience", "status", "recipients_count"),
        fk_fields=(),
    ),
}


@dataclass
class UniversityMemoryState:
    data: dict[str, dict[int, dict[str, object]]] = field(default_factory=dict)
    counters: dict[str, int] = field(default_factory=dict)


_state_lock = Lock()
_state = UniversityMemoryState(
    data={name: {} for name in ENTITY_CONFIGS},
    counters={name: 0 for name in ENTITY_CONFIGS},
)


def clear_university_state() -> None:
    with _state_lock:
        for name in ENTITY_CONFIGS:
            _state.data[name].clear()
            _state.counters[name] = 0


__all__ = [
    "EntityConfig",
    "ENTITY_CONFIGS",
    "UniversityMemoryState",
    "_state",
    "_state_lock",
    "clear_university_state",
    "get_raw_conn",
    "psycopg",
]
