import { apiGet, apiPost } from '@/shared/api/client';
import { DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS } from './constants';
import type {
  DdcArchiveReadiness,
  DdcAssignmentBridge,
  DdcAttachmentMetadata,
  DdcAuditEvent,
  DdcBridge,
  DdcCommitteeDecisionBridge,
  DdcDashboard,
  DdcDecreeDraft,
  DdcDecreeRegistry,
  DdcDeliveryReadiness,
  DdcDocumentIntake,
  DdcDocumentRegistration,
  DdcDocumentRouting,
  DdcEvidenceItem,
  DdcExecutionControl,
  DdcIncomingCorrespondence,
  DdcLimitations,
  DdcMetadataContract,
  DdcOutgoingCorrespondence,
  DdcOverview,
  DdcPermission,
  DdcReadiness,
  DdcRectorResolution,
  DdcRetentionMetadata,
  DdcRole,
  DdcSignatureReadiness,
  DdcSlaDeadline,
  DdcTemplateMetadata,
} from './types';

type Payload<T> = Partial<T> & Record<string, unknown>;

export const documentDecreeCorrespondenceApi = {
  getDdcOverview: () => apiGet<DdcOverview>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.overview),
  getDdcReadiness: () => apiGet<DdcReadiness>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.readiness),
  getDdcLimitations: () => apiGet<DdcLimitations[]>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.limitations),
  getDdcSafetyBoundaries: () => apiGet<Record<string, unknown>>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.safetyBoundaries),
  getDdcDashboard: () => apiGet<DdcDashboard>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.dashboard),
  getDdcDocuments: () => apiGet<DdcDocumentRegistration[]>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.documents),
  getDdcDocumentIntake: () => apiGet<DdcDocumentIntake[]>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.documentIntake),
  getDdcDocumentRouting: () => apiGet<DdcDocumentRouting[]>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.documentRouting),
  getDdcRectorResolutions: () => apiGet<DdcRectorResolution[]>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.rectorResolutions),
  getDdcDecrees: () => apiGet<DdcDecreeRegistry[]>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.decrees),
  getDdcDecreeDrafts: () => apiGet<DdcDecreeDraft[]>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.decreeDrafts),
  getDdcIncomingCorrespondence: () => apiGet<DdcIncomingCorrespondence[]>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.incomingCorrespondence),
  getDdcOutgoingCorrespondence: () => apiGet<DdcOutgoingCorrespondence[]>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.outgoingCorrespondence),
  getDdcTemplates: () => apiGet<DdcTemplateMetadata[]>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.templates),
  getDdcCommitteeDecisions: () => apiGet<DdcCommitteeDecisionBridge[]>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.committeeDecisions),
  getDdcAssignments: () => apiGet<DdcAssignmentBridge[]>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.assignments),
  getDdcExecutionControl: () => apiGet<DdcExecutionControl[]>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.executionControl),
  getDdcSlaDeadlines: () => apiGet<DdcSlaDeadline[]>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.slaDeadlines),
  getDdcEvidence: () => apiGet<DdcEvidenceItem[]>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.evidence),
  getDdcAttachments: () => apiGet<DdcAttachmentMetadata[]>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.attachments),
  getDdcAuditEvents: () => apiGet<DdcAuditEvent[]>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.auditEvents),
  getDdcArchive: () => apiGet<DdcArchiveReadiness[]>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.archive),
  getDdcSignatureReadiness: () => apiGet<DdcSignatureReadiness[]>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.signatureReadiness),
  getDdcDeliveryReadiness: () => apiGet<DdcDeliveryReadiness[]>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.deliveryReadiness),
  getDdcBridgeExecutive: () => apiGet<DdcBridge[]>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.bridgesExecutive),
  getDdcBridgeAssignments: () => apiGet<DdcBridge[]>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.bridgesAssignments),
  getDdcHealth: () => apiGet<Record<string, unknown>>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.health),
  getDdcRoles: () => apiGet<DdcRole[]>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.roles),
  getDdcPermissions: () => apiGet<DdcPermission[]>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.permissions),
  getDdcMetadataContract: () => apiGet<DdcMetadataContract>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.metadataContract),

  createDdcDocumentIntake: (payload: Payload<DdcDocumentIntake>) => apiPost<Record<string, unknown>>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.documentIntake, payload),
  createDdcDocumentRegistrationMetadata: (payload: Payload<DdcDocumentRegistration>) => apiPost<Record<string, unknown>>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.documentRegistration, payload),
  createDdcDocumentRoutingMetadata: (payload: Payload<DdcDocumentRouting>) => apiPost<Record<string, unknown>>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.documentRouting, payload),
  createDdcRectorResolutionMetadata: (payload: Payload<DdcRectorResolution>) => apiPost<Record<string, unknown>>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.rectorResolutionsMetadata, payload),
  createDdcDecreeMetadata: (payload: Payload<DdcDecreeRegistry>) => apiPost<Record<string, unknown>>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.decreesMetadata, payload),
  createDdcDecreeDraft: (payload: Payload<DdcDecreeDraft>) => apiPost<Record<string, unknown>>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.decreeDrafts, payload),
  createDdcIncomingCorrespondence: (payload: Payload<DdcIncomingCorrespondence>) => apiPost<Record<string, unknown>>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.incomingCorrespondence, payload),
  createDdcOutgoingCorrespondence: (payload: Payload<DdcOutgoingCorrespondence>) => apiPost<Record<string, unknown>>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.outgoingCorrespondence, payload),
  createDdcTemplateMetadata: (payload: Payload<DdcTemplateMetadata>) => apiPost<Record<string, unknown>>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.templatesMetadata, payload),
  createDdcCommitteeDecisionBridge: (payload: Payload<DdcCommitteeDecisionBridge>) => apiPost<Record<string, unknown>>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.committeeDecisionsBridge, payload),
  createDdcAssignmentBridge: (payload: Payload<DdcAssignmentBridge>) => apiPost<Record<string, unknown>>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.assignmentsBridge, payload),
  createDdcExecutionControlMetadata: (payload: Payload<DdcExecutionControl>) => apiPost<Record<string, unknown>>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.executionControlMetadata, payload),
  createDdcSlaDeadline: (payload: Payload<DdcSlaDeadline>) => apiPost<Record<string, unknown>>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.slaDeadlines, payload),
  createDdcEvidence: (payload: Payload<DdcEvidenceItem>) => apiPost<Record<string, unknown>>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.evidence, payload),
  createDdcAttachmentMetadata: (payload: Payload<DdcAttachmentMetadata>) => apiPost<Record<string, unknown>>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.attachmentsMetadata, payload),
  createDdcAuditEvent: (payload: Payload<DdcAuditEvent>) => apiPost<Record<string, unknown>>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.auditEvents, payload),
  createDdcArchiveReadiness: (payload: Payload<DdcArchiveReadiness>) => apiPost<Record<string, unknown>>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.archiveReadiness, payload),
  createDdcRetentionMetadata: (payload: Payload<DdcRetentionMetadata>) => apiPost<Record<string, unknown>>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.retentionMetadata, payload),
  createDdcSignatureReadinessEvidence: (payload: Payload<DdcSignatureReadiness>) => apiPost<Record<string, unknown>>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.signatureReadinessEvidence, payload),
  createDdcDeliveryReadinessEvidence: (payload: Payload<DdcDeliveryReadiness>) => apiPost<Record<string, unknown>>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.deliveryReadinessEvidence, payload),
  createDdcBridgeExecutive: (payload: Payload<DdcBridge>) => apiPost<Record<string, unknown>>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.bridgesExecutive, payload),
  createDdcBridgeAssignments: (payload: Payload<DdcBridge>) => apiPost<Record<string, unknown>>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.bridgesAssignments, payload),
  createDdcLimitation: (payload: Payload<DdcLimitations>) => apiPost<Record<string, unknown>>(DOCUMENT_DECREE_CORRESPONDENCE_API_PATHS.limitations, payload),
};
