import type { DdcRouteKey } from './types';

export const DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS = {
  metadataEvidenceOnlyDocumentFoundation: 'Metadata/evidence-only document foundation',
  humanReviewRequired: 'Human review required',
  noFakeOfficialDocuments: 'No fake official documents',
  noFakeDecrees: 'No fake decrees',
  noFakeSignatures: 'No fake signatures',
  noFakeDeliveryConfirmations: 'No fake delivery confirmations',
  noOfficialLegalEffect: 'No official legal effect',
  noAutomaticRectorDecision: 'No automatic rector decision',
  noAutomaticDecreeApproval: 'No automatic decree approval',
  noAutomaticDocumentSigning: 'No automatic document signing',
  noExternalMinistrySubmission: 'No external ministry/eGov submission',
  noHiddenStaffDepartmentScore: 'No hidden staff/department score',
  signatureReadinessOnly: 'Signature readiness only',
  deliveryReadinessOnly: 'Delivery readiness only',
  archiveReadinessOnly: 'Archive readiness only',
  incompleteDataSupported: 'Incomplete data supported',
  bridgeFirstReadOnlyFirst: 'Bridge-first / read-only-first',
  noProductionReadyClaim: 'No production-ready claim',
  noSalesReadyClaim: 'No sales-ready claim',
  noGccReadyClaim: 'No GCC-ready claim',
  fakeDocumentsFalse: 'fakeDocuments=false',
  fakeDecreesFalse: 'fakeDecrees=false',
  fakeSignaturesFalse: 'fakeSignatures=false',
  fakeDeliveryConfirmationsFalse: 'fakeDeliveryConfirmations=false',
  fakeArchiveLegalRecordFalse: 'fakeArchiveLegalRecord=false',
  officialLegalEffectFalse: 'officialLegalEffect=false',
  externalSubmissionEnabledFalse: 'externalSubmissionEnabled=false',
  automaticRectorDecisionEnabledFalse: 'automaticRectorDecisionEnabled=false',
  automaticDecreeApprovalEnabledFalse: 'automaticDecreeApprovalEnabled=false',
  automaticDocumentSigningEnabledFalse: 'automaticDocumentSigningEnabled=false',
  hiddenScorePresentFalse: 'hiddenScorePresent=false',
} as const;

export const DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_COPY = [
  DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.metadataEvidenceOnlyDocumentFoundation,
  DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.humanReviewRequired,
  DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.noFakeOfficialDocuments,
  DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.noFakeDecrees,
  DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.noFakeSignatures,
  DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.noFakeDeliveryConfirmations,
  DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.noOfficialLegalEffect,
  DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.noAutomaticRectorDecision,
  DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.noAutomaticDecreeApproval,
  DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.noAutomaticDocumentSigning,
  DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.noExternalMinistrySubmission,
  DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.noHiddenStaffDepartmentScore,
  DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.signatureReadinessOnly,
  DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.deliveryReadinessOnly,
  DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.archiveReadinessOnly,
  DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.incompleteDataSupported,
  DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.bridgeFirstReadOnlyFirst,
  DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.noProductionReadyClaim,
  DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.noSalesReadyClaim,
  DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.noGccReadyClaim,
] as const;

export const DOCUMENT_DECREE_CORRESPONDENCE_FORBIDDEN_LABELS = [
  'Sign document',
  'Issue official decree',
  'Approve decree automatically',
  'Rector decision auto',
  'Submit to ministry',
  'Send external delivery',
  'Confirm legal archive',
  'Fake signature',
  'Fake decree',
  'Fake document',
  'Hidden staff score',
  'Hidden department score',
  'Production ready',
  'Sales ready',
  'GCC ready',
  'L5/L6 ready',
] as const;

export const DOCUMENT_DECREE_CORRESPONDENCE_PAGE_BOUNDARY_LABELS: Record<DdcRouteKey, string[]> = {
  overview: [
    ...DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_COPY,
    DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.fakeDocumentsFalse,
    DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.fakeDecreesFalse,
    DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.fakeSignaturesFalse,
  ],
  dashboard: [
    DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.metadataEvidenceOnlyDocumentFoundation,
    DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.incompleteDataSupported,
    DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.humanReviewRequired,
  ],
  documents: [DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.metadataEvidenceOnlyDocumentFoundation, DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.noFakeOfficialDocuments],
  intake: [DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.humanReviewRequired, DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.noFakeOfficialDocuments],
  routing: [DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.humanReviewRequired, DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.bridgeFirstReadOnlyFirst],
  'rector-resolutions': [DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.noAutomaticRectorDecision, DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.humanReviewRequired],
  decrees: [DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.noAutomaticDecreeApproval, DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.noOfficialLegalEffect],
  'decree-drafts': [DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.humanReviewRequired, DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.noAutomaticDecreeApproval],
  incoming: [DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.metadataEvidenceOnlyDocumentFoundation, DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.incompleteDataSupported],
  outgoing: [DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.metadataEvidenceOnlyDocumentFoundation, DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.noExternalMinistrySubmission],
  templates: [DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.metadataEvidenceOnlyDocumentFoundation, DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.humanReviewRequired],
  'committee-decisions': [DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.humanReviewRequired, DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.bridgeFirstReadOnlyFirst],
  assignments: [DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.humanReviewRequired, DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.bridgeFirstReadOnlyFirst],
  'execution-control': [DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.humanReviewRequired, DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.noAutomaticDocumentSigning],
  'sla-deadlines': [DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.humanReviewRequired, DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.incompleteDataSupported],
  evidence: [DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.metadataEvidenceOnlyDocumentFoundation, DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.humanReviewRequired],
  attachments: [DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.metadataEvidenceOnlyDocumentFoundation, DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.incompleteDataSupported],
  audit: [DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.humanReviewRequired, DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.metadataEvidenceOnlyDocumentFoundation],
  archive: [DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.archiveReadinessOnly, DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.noOfficialLegalEffect],
  'signature-readiness': [DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.signatureReadinessOnly, DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.noAutomaticDocumentSigning],
  'delivery-readiness': [DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.deliveryReadinessOnly, DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.noExternalMinistrySubmission],
  bridges: [DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.bridgeFirstReadOnlyFirst, DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_LABELS.noHiddenStaffDepartmentScore],
  limitations: [...DOCUMENT_DECREE_CORRESPONDENCE_BOUNDARY_COPY],
};

export function getDdcBoundaryLabels(routeKey: DdcRouteKey) {
  return DOCUMENT_DECREE_CORRESPONDENCE_PAGE_BOUNDARY_LABELS[routeKey];
}
