"""Research / Science backend foundation module."""

from app.modules.research_science import (
    dependencies,
    models,
    permissions,
    repository,
    router,
    schemas,
    service,
)

MODULE_NAME = "research_science"
TABLE_PREFIX = "rs_"
TARGET_LEVEL = "L3"
CONTRACT_VERSION = "A-037.2"
FOUNDATION_STATUS = "RESEARCH_SCIENCE_METADATA_EVIDENCE_BACKEND_FOUNDATION"
MASTER_MATRIX_COMMIT = "c79cc31"
MASTER_MATRIX_ROW_COUNT = 467
SOURCE_SPEC_COMMIT = "02b5564"
SOURCE_PRODUCT_MAP_COMMIT = "10d833e"
PRODUCT_VERTICAL = "Research / Science Suite"
RESEARCH_SCIENCE_CAPABILITY_COUNT = 60
RUNTIME_MODE = "METADATA_EVIDENCE_ONLY"
DATA_SOURCE = "computed_from_research_science_metadata"
OFFICIAL_VERIFICATION_MODE = "NOT_IMPLEMENTED"
PROVIDER_INTEGRATION_MODE = "FUTURE_READINESS_ONLY"
AUTONOMY_MODE = "FORBIDDEN"

PROVIDER_INTEGRATION_ENABLED = False
EXTERNAL_DATABASE_SYNC_ENABLED = False
OFFICIAL_VERIFICATION_ENABLED = False
AUTONOMOUS_DECISION_ENABLED = False
HIDDEN_SCORE_PRESENT = False
FAKE_METRICS = False
HUMAN_REVIEW_REQUIRED = True

__all__ = [
    "AUTONOMOUS_DECISION_ENABLED",
    "AUTONOMY_MODE",
    "CONTRACT_VERSION",
    "DATA_SOURCE",
    "EXTERNAL_DATABASE_SYNC_ENABLED",
    "FAKE_METRICS",
    "FOUNDATION_STATUS",
    "HIDDEN_SCORE_PRESENT",
    "HUMAN_REVIEW_REQUIRED",
    "MASTER_MATRIX_COMMIT",
    "MASTER_MATRIX_ROW_COUNT",
    "MODULE_NAME",
    "OFFICIAL_VERIFICATION_ENABLED",
    "OFFICIAL_VERIFICATION_MODE",
    "PRODUCT_VERTICAL",
    "PROVIDER_INTEGRATION_ENABLED",
    "PROVIDER_INTEGRATION_MODE",
    "RESEARCH_SCIENCE_CAPABILITY_COUNT",
    "RUNTIME_MODE",
    "SOURCE_PRODUCT_MAP_COMMIT",
    "SOURCE_SPEC_COMMIT",
    "TABLE_PREFIX",
    "TARGET_LEVEL",
    "dependencies",
    "models",
    "permissions",
    "repository",
    "router",
    "schemas",
    "service",
]