[pytest]
filterwarnings =
    ignore:.*asyncio\.iscoroutinefunction.*:DeprecationWarning:fastapi\.routing
    ignore:tagMap is deprecated\. Please use TAG_MAP instead\.:DeprecationWarning:pyasn1\.codec\.ber\.encoder
    ignore:typeMap is deprecated\. Please use TYPE_MAP instead\.:DeprecationWarning:pyasn1\.codec\.ber\.encoder
    ignore:.*on_event is deprecated, use lifespan event handlers instead.*:DeprecationWarning:fastapi\.applications
