import { apiGet, apiPost } from '@/shared/api/client';
import { FINANCE_PROCUREMENT_ASSET_API_PATHS } from './constants';
import type {
  FpaAssetLifecycle,
  FpaAssetVisibility,
  FpaAuditEvent,
  FpaBankReadiness,
  FpaBillingVisibility,
  FpaBridgeRecordsResponse,
  FpaBridgeSummary,
  FpaBudgetControl,
  FpaBudgetPlan,
  FpaContractEvidence,
  FpaDashboardSummary,
  FpaErpReadiness,
  FpaEvidenceItem,
  FpaInventoryMovementMetadata,
  FpaLimitations,
  FpaOverview,
  FpaPaymentGatewayReadiness,
  FpaPaymentReadiness,
  FpaPermission,
  FpaProcurementRequest,
  FpaProcurementReview,
  FpaProviderReadiness,
  FpaPurchaseOrderMetadata,
  FpaPurchaseRequest,
  FpaReadiness,
  FpaReceivablesMetadata,
  FpaRole,
  FpaMetadataContract,
  FpaVendorMetadata,
} from './types';

type Payload<T> = Partial<T> & Record<string, unknown>;

export const financeProcurementAssetApi = {
  getFpaOverview: () => apiGet<FpaOverview>(FINANCE_PROCUREMENT_ASSET_API_PATHS.overview),
  getFpaReadiness: () => apiGet<FpaReadiness>(FINANCE_PROCUREMENT_ASSET_API_PATHS.readiness),
  getFpaLimitations: () => apiGet<FpaLimitations[]>(FINANCE_PROCUREMENT_ASSET_API_PATHS.limitations),
  getFpaSafetyBoundaries: () => apiGet<Record<string, unknown>>(FINANCE_PROCUREMENT_ASSET_API_PATHS.safetyBoundaries),
  getFpaDashboard: () => apiGet<FpaDashboardSummary>(FINANCE_PROCUREMENT_ASSET_API_PATHS.dashboard),
  getFpaBilling: () => apiGet<FpaBillingVisibility[]>(FINANCE_PROCUREMENT_ASSET_API_PATHS.billing),
  getFpaReceivables: () => apiGet<FpaReceivablesMetadata[]>(FINANCE_PROCUREMENT_ASSET_API_PATHS.receivables),
  getFpaBudgetPlans: () => apiGet<FpaBudgetPlan[]>(FINANCE_PROCUREMENT_ASSET_API_PATHS.budgetPlans),
  getFpaBudgetControls: () => apiGet<FpaBudgetControl[]>(FINANCE_PROCUREMENT_ASSET_API_PATHS.budgetControls),
  getFpaProcurementRequests: () => apiGet<FpaProcurementRequest[]>(FINANCE_PROCUREMENT_ASSET_API_PATHS.procurementRequests),
  getFpaProcurementReviews: () => apiGet<FpaProcurementReview[]>(FINANCE_PROCUREMENT_ASSET_API_PATHS.procurementReviews),
  getFpaVendors: () => apiGet<FpaVendorMetadata[]>(FINANCE_PROCUREMENT_ASSET_API_PATHS.vendors),
  getFpaContracts: () => apiGet<FpaContractEvidence[]>(FINANCE_PROCUREMENT_ASSET_API_PATHS.contracts),
  getFpaPurchaseRequests: () => apiGet<FpaPurchaseRequest[]>(FINANCE_PROCUREMENT_ASSET_API_PATHS.purchaseRequests),
  getFpaPurchaseOrders: () => apiGet<FpaPurchaseOrderMetadata[]>(FINANCE_PROCUREMENT_ASSET_API_PATHS.purchaseOrders),
  getFpaAssets: () => apiGet<FpaAssetVisibility[]>(FINANCE_PROCUREMENT_ASSET_API_PATHS.assets),
  getFpaAssetLifecycle: () => apiGet<FpaAssetLifecycle[]>(FINANCE_PROCUREMENT_ASSET_API_PATHS.assetLifecycle),
  getFpaInventoryMovements: () => apiGet<FpaInventoryMovementMetadata[]>(FINANCE_PROCUREMENT_ASSET_API_PATHS.inventoryMovements),
  getFpaPaymentReadiness: () => apiGet<FpaPaymentReadiness[]>(FINANCE_PROCUREMENT_ASSET_API_PATHS.paymentReadiness),
  getFpaErpReadiness: () => apiGet<FpaErpReadiness[]>(FINANCE_PROCUREMENT_ASSET_API_PATHS.erpReadiness),
  getFpaBankReadiness: () => apiGet<FpaBankReadiness[]>(FINANCE_PROCUREMENT_ASSET_API_PATHS.bankReadiness),
  getFpaPaymentGatewayReadiness: () => apiGet<FpaPaymentGatewayReadiness[]>(FINANCE_PROCUREMENT_ASSET_API_PATHS.paymentGatewayReadiness),
  getFpaProviderReadiness: () => apiGet<FpaProviderReadiness[]>(FINANCE_PROCUREMENT_ASSET_API_PATHS.providerReadiness),
  getFpaAuditEvents: () => apiGet<FpaAuditEvent[]>(FINANCE_PROCUREMENT_ASSET_API_PATHS.auditEvents),
  getFpaEvidence: () => apiGet<FpaEvidenceItem[]>(FINANCE_PROCUREMENT_ASSET_API_PATHS.evidence),
  getFpaBridgeExecutive: () => apiGet<FpaBridgeSummary>(FINANCE_PROCUREMENT_ASSET_API_PATHS.bridgeExecutive),
  getFpaBridgeHrPayroll: () => apiGet<FpaBridgeSummary>(FINANCE_PROCUREMENT_ASSET_API_PATHS.bridgeHrPayroll),
  getFpaBridgeDocumentContracts: () => apiGet<FpaBridgeSummary>(FINANCE_PROCUREMENT_ASSET_API_PATHS.bridgeDocumentContracts),
  getFpaBridgeProviderReadiness: () => apiGet<FpaBridgeSummary>(FINANCE_PROCUREMENT_ASSET_API_PATHS.bridgeProviderReadiness),
  getFpaBridgeStudentFinance: () => apiGet<FpaBridgeSummary>(FINANCE_PROCUREMENT_ASSET_API_PATHS.bridgeStudentFinance),
  getFpaBridgeStudentFinanceReferrals: () => apiGet<FpaBridgeRecordsResponse>(FINANCE_PROCUREMENT_ASSET_API_PATHS.bridgeStudentFinanceReferrals),
  acknowledgeFpaStudentFinanceReferral: (payload: Record<string, unknown>) => apiPost<Record<string, unknown>>(FINANCE_PROCUREMENT_ASSET_API_PATHS.bridgeStudentFinanceReferralAcknowledge, payload),
  getFpaHealth: () => apiGet<Record<string, unknown>>(FINANCE_PROCUREMENT_ASSET_API_PATHS.health),
  getFpaRoles: () => apiGet<FpaRole[]>(FINANCE_PROCUREMENT_ASSET_API_PATHS.roles),
  getFpaPermissions: () => apiGet<FpaPermission[]>(FINANCE_PROCUREMENT_ASSET_API_PATHS.permissions),
  getFpaMetadataContract: () => apiGet<FpaMetadataContract>(FINANCE_PROCUREMENT_ASSET_API_PATHS.metadataContract),

  createFpaReadinessEvidence: (payload: Payload<FpaReadiness>) => apiPost<Record<string, unknown>>(FINANCE_PROCUREMENT_ASSET_API_PATHS.readinessEvidence, payload),
  createFpaBillingEvidence: (payload: Payload<FpaBillingVisibility>) => apiPost<Record<string, unknown>>(FINANCE_PROCUREMENT_ASSET_API_PATHS.billingEvidence, payload),
  createFpaReceivablesMetadata: (payload: Payload<FpaReceivablesMetadata>) => apiPost<Record<string, unknown>>(FINANCE_PROCUREMENT_ASSET_API_PATHS.receivablesMetadata, payload),
  createFpaBudgetPlan: (payload: Payload<FpaBudgetPlan>) => apiPost<Record<string, unknown>>(FINANCE_PROCUREMENT_ASSET_API_PATHS.budgetPlans, payload),
  reviewFpaBudgetControl: (payload: Payload<FpaBudgetControl>) => apiPost<Record<string, unknown>>(FINANCE_PROCUREMENT_ASSET_API_PATHS.budgetControlsReview, payload),
  createFpaProcurementRequest: (payload: Payload<FpaProcurementRequest>) => apiPost<Record<string, unknown>>(FINANCE_PROCUREMENT_ASSET_API_PATHS.procurementRequests, payload),
  reviewFpaProcurement: (payload: Payload<FpaProcurementReview>) => apiPost<Record<string, unknown>>(FINANCE_PROCUREMENT_ASSET_API_PATHS.procurementReviews, payload),
  createFpaVendorMetadata: (payload: Payload<FpaVendorMetadata>) => apiPost<Record<string, unknown>>(FINANCE_PROCUREMENT_ASSET_API_PATHS.vendors, payload),
  createFpaContractEvidence: (payload: Payload<FpaContractEvidence>) => apiPost<Record<string, unknown>>(FINANCE_PROCUREMENT_ASSET_API_PATHS.contractsEvidence, payload),
  createFpaPurchaseRequest: (payload: Payload<FpaPurchaseRequest>) => apiPost<Record<string, unknown>>(FINANCE_PROCUREMENT_ASSET_API_PATHS.purchaseRequests, payload),
  createFpaPurchaseOrderMetadata: (payload: Payload<FpaPurchaseOrderMetadata>) => apiPost<Record<string, unknown>>(FINANCE_PROCUREMENT_ASSET_API_PATHS.purchaseOrdersMetadata, payload),
  createFpaAssetMetadata: (payload: Payload<FpaAssetVisibility>) => apiPost<Record<string, unknown>>(FINANCE_PROCUREMENT_ASSET_API_PATHS.assetsMetadata, payload),
  createFpaAssetLifecycle: (payload: Payload<FpaAssetLifecycle>) => apiPost<Record<string, unknown>>(FINANCE_PROCUREMENT_ASSET_API_PATHS.assetLifecycle, payload),
  createFpaInventoryMovementMetadata: (payload: Payload<FpaInventoryMovementMetadata>) => apiPost<Record<string, unknown>>(FINANCE_PROCUREMENT_ASSET_API_PATHS.inventoryMovementsMetadata, payload),
  createFpaPaymentReadinessEvidence: (payload: Payload<FpaPaymentReadiness>) => apiPost<Record<string, unknown>>(FINANCE_PROCUREMENT_ASSET_API_PATHS.paymentReadinessEvidence, payload),
  createFpaErpReadinessEvidence: (payload: Payload<FpaErpReadiness>) => apiPost<Record<string, unknown>>(FINANCE_PROCUREMENT_ASSET_API_PATHS.erpReadinessEvidence, payload),
  createFpaBankReadinessEvidence: (payload: Payload<FpaBankReadiness>) => apiPost<Record<string, unknown>>(FINANCE_PROCUREMENT_ASSET_API_PATHS.bankReadinessEvidence, payload),
  createFpaPaymentGatewayReadinessEvidence: (payload: Payload<FpaPaymentGatewayReadiness>) => apiPost<Record<string, unknown>>(FINANCE_PROCUREMENT_ASSET_API_PATHS.paymentGatewayReadinessEvidence, payload),
  createFpaProviderReadinessEvidence: (payload: Payload<FpaProviderReadiness>) => apiPost<Record<string, unknown>>(FINANCE_PROCUREMENT_ASSET_API_PATHS.providerReadinessEvidence, payload),
  createFpaEvidence: (payload: Payload<FpaEvidenceItem>) => apiPost<Record<string, unknown>>(FINANCE_PROCUREMENT_ASSET_API_PATHS.evidence, payload),
  createFpaAuditEvent: (payload: Payload<FpaAuditEvent>) => apiPost<Record<string, unknown>>(FINANCE_PROCUREMENT_ASSET_API_PATHS.auditEvents, payload),
};
