import { apiGet, apiPost } from '@/shared/api/client';
import { SECURITY_ACCESS_COMPLIANCE_API_BASE } from './constants';
import type {
  SacAbacEvidence,
  SacAccessGovernance,
  SacApiResult,
  SacAuditEventReview,
  SacComplianceControl,
  SacCrossVerticalBridge,
  SacDashboard,
  SacDataProtectionReadiness,
  SacIncidentReview,
  SacLimitations,
  SacLoginEventReview,
  SacMetadataContract,
  SacMfaReadiness,
  SacOverview,
  SacPermissionRecord,
  SacPolicyControlBridge,
  SacPrivacyReadiness,
  SacReadiness,
  SacRemediationTracking,
  SacRiskRegister,
  SacRbacEvidence,
  SacRole,
  SacSecurityException,
  SacSecurityIncident,
  SacSensitiveActionReview,
  SacSessionVisibility,
  SacTenantIsolationEvidence,
  SacVisitorAccessBridge,
} from './types';

// Intentionally keep response shapes lightweight and contract-oriented.
type SacListResponse<T> = SacApiResult<{ items: T[] }>;
type SacItemResponse<T> = SacApiResult<{ item: T }>;

function apiPath(path: string) {
  return `${SECURITY_ACCESS_COMPLIANCE_API_BASE}${path}`;
}

export const SECURITY_ACCESS_COMPLIANCE_API_PATHS = {
  overview: apiPath('/overview'),
  readiness: apiPath('/readiness'),
  dashboard: apiPath('/dashboard'),
  limitations: apiPath('/limitations'),
  roles: apiPath('/roles'),
  permissions: apiPath('/permissions'),
  accessGovernance: apiPath('/access-governance'),
  rbacEvidence: apiPath('/rbac-evidence'),
  abacEvidence: apiPath('/abac-evidence'),
  sessions: apiPath('/sessions'),
  loginEvents: apiPath('/login-events'),
  mfaReadiness: apiPath('/mfa-readiness'),
  tenantIsolation: apiPath('/tenant-isolation'),
  incidents: apiPath('/incidents'),
  incidentReview: apiPath('/incident-review'),
  remediation: apiPath('/remediation'),
  risks: apiPath('/risks'),
  complianceControls: apiPath('/compliance-controls'),
  policyControls: apiPath('/policy-controls'),
  auditEvents: apiPath('/audit-events'),
  sensitiveActions: apiPath('/sensitive-actions'),
  dataProtection: apiPath('/data-protection'),
  privacyReadiness: apiPath('/privacy-readiness'),
  exceptions: apiPath('/exceptions'),
  visitorAccess: apiPath('/visitor-access'),
  bridgeHr: apiPath('/bridges/hr'),
  bridgeFinance: apiPath('/bridges/finance'),
  bridgeDocuments: apiPath('/bridges/documents'),
  bridgeStudentServices: apiPath('/bridges/student-services'),
  metadataContract: apiPath('/metadata-contract'),
  safetyBoundaries: apiPath('/limitations'),
  health: apiPath('/metadata-contract'),
  incidentMetadata: apiPath('/incidents/metadata'),
  incidentReviewMetadata: apiPath('/incident-review/metadata'),
  remediationMetadata: apiPath('/remediation/metadata'),
  risksMetadata: apiPath('/risks/metadata'),
  complianceControlsMetadata: apiPath('/compliance-controls/metadata'),
  policyControlsMetadata: apiPath('/policy-controls/metadata'),
  auditEventsMetadata: apiPath('/audit-events/metadata'),
  sensitiveActionsReview: apiPath('/sensitive-actions/review'),
  dataProtectionEvidence: apiPath('/data-protection/evidence'),
  privacyReadinessEvidence: apiPath('/privacy-readiness/evidence'),
  exceptionsMetadata: apiPath('/exceptions/metadata'),
  visitorAccessMetadata: apiPath('/visitor-access/metadata'),
  limitation: apiPath('/limitations'),
} as const;

export const securityAccessComplianceApi = {
  getSacOverview: () => apiGet<SacOverview>(SECURITY_ACCESS_COMPLIANCE_API_PATHS.overview),
  getSacReadiness: () => apiGet<SacReadiness>(SECURITY_ACCESS_COMPLIANCE_API_PATHS.readiness),
  getSacDashboard: () => apiGet<SacDashboard>(SECURITY_ACCESS_COMPLIANCE_API_PATHS.dashboard),
  getSacLimitations: () => apiGet<SacLimitations>(SECURITY_ACCESS_COMPLIANCE_API_PATHS.limitations),
  getSacRoles: () => apiGet<SacListResponse<SacRole>>(SECURITY_ACCESS_COMPLIANCE_API_PATHS.roles),
  getSacPermissions: () => apiGet<SacListResponse<SacPermissionRecord>>(SECURITY_ACCESS_COMPLIANCE_API_PATHS.permissions),
  getSacAccessGovernance: () => apiGet<SacAccessGovernance>(SECURITY_ACCESS_COMPLIANCE_API_PATHS.accessGovernance),
  getSacRbacEvidence: () => apiGet<SacRbacEvidence>(SECURITY_ACCESS_COMPLIANCE_API_PATHS.rbacEvidence),
  getSacAbacEvidence: () => apiGet<SacAbacEvidence>(SECURITY_ACCESS_COMPLIANCE_API_PATHS.abacEvidence),
  getSacSessions: () => apiGet<SacSessionVisibility>(SECURITY_ACCESS_COMPLIANCE_API_PATHS.sessions),
  getSacLoginEvents: () => apiGet<SacLoginEventReview>(SECURITY_ACCESS_COMPLIANCE_API_PATHS.loginEvents),
  getSacMfaReadiness: () => apiGet<SacMfaReadiness>(SECURITY_ACCESS_COMPLIANCE_API_PATHS.mfaReadiness),
  getSacTenantIsolation: () => apiGet<SacTenantIsolationEvidence>(SECURITY_ACCESS_COMPLIANCE_API_PATHS.tenantIsolation),
  getSacIncidents: () => apiGet<SacSecurityIncident>(SECURITY_ACCESS_COMPLIANCE_API_PATHS.incidents),
  getSacIncidentReview: () => apiGet<SacIncidentReview>(SECURITY_ACCESS_COMPLIANCE_API_PATHS.incidentReview),
  getSacRemediation: () => apiGet<SacRemediationTracking>(SECURITY_ACCESS_COMPLIANCE_API_PATHS.remediation),
  getSacRisks: () => apiGet<SacRiskRegister>(SECURITY_ACCESS_COMPLIANCE_API_PATHS.risks),
  getSacComplianceControls: () => apiGet<SacComplianceControl>(SECURITY_ACCESS_COMPLIANCE_API_PATHS.complianceControls),
  getSacPolicyControls: () => apiGet<SacPolicyControlBridge>(SECURITY_ACCESS_COMPLIANCE_API_PATHS.policyControls),
  getSacAuditEvents: () => apiGet<SacAuditEventReview>(SECURITY_ACCESS_COMPLIANCE_API_PATHS.auditEvents),
  getSacSensitiveActions: () => apiGet<SacSensitiveActionReview>(SECURITY_ACCESS_COMPLIANCE_API_PATHS.sensitiveActions),
  getSacDataProtection: () => apiGet<SacDataProtectionReadiness>(SECURITY_ACCESS_COMPLIANCE_API_PATHS.dataProtection),
  getSacPrivacyReadiness: () => apiGet<SacPrivacyReadiness>(SECURITY_ACCESS_COMPLIANCE_API_PATHS.privacyReadiness),
  getSacExceptions: () => apiGet<SacSecurityException>(SECURITY_ACCESS_COMPLIANCE_API_PATHS.exceptions),
  getSacVisitorAccess: () => apiGet<SacVisitorAccessBridge>(SECURITY_ACCESS_COMPLIANCE_API_PATHS.visitorAccess),
  getSacBridgeHr: () => apiGet<SacCrossVerticalBridge>(SECURITY_ACCESS_COMPLIANCE_API_PATHS.bridgeHr),
  getSacBridgeFinance: () => apiGet<SacCrossVerticalBridge>(SECURITY_ACCESS_COMPLIANCE_API_PATHS.bridgeFinance),
  getSacBridgeDocuments: () => apiGet<SacCrossVerticalBridge>(SECURITY_ACCESS_COMPLIANCE_API_PATHS.bridgeDocuments),
  getSacBridgeStudentServices: () => apiGet<SacCrossVerticalBridge>(SECURITY_ACCESS_COMPLIANCE_API_PATHS.bridgeStudentServices),
  getSacMetadataContract: () => apiGet<SacMetadataContract>(SECURITY_ACCESS_COMPLIANCE_API_PATHS.metadataContract),
  getSacSafetyBoundaries: () => apiGet<SacLimitations>(SECURITY_ACCESS_COMPLIANCE_API_PATHS.safetyBoundaries),
  getSacHealth: () => apiGet<SacMetadataContract>(SECURITY_ACCESS_COMPLIANCE_API_PATHS.health),

  createSacIncidentMetadata: (payload: unknown) => apiPost<SacItemResponse<unknown>>(SECURITY_ACCESS_COMPLIANCE_API_PATHS.incidentMetadata, payload),
  createSacIncidentReviewMetadata: (payload: unknown) => apiPost<SacItemResponse<unknown>>(SECURITY_ACCESS_COMPLIANCE_API_PATHS.incidentReviewMetadata, payload),
  createSacRemediationMetadata: (payload: unknown) => apiPost<SacItemResponse<unknown>>(SECURITY_ACCESS_COMPLIANCE_API_PATHS.remediationMetadata, payload),
  createSacRiskMetadata: (payload: unknown) => apiPost<SacItemResponse<unknown>>(SECURITY_ACCESS_COMPLIANCE_API_PATHS.risksMetadata, payload),
  createSacComplianceControlMetadata: (payload: unknown) => apiPost<SacItemResponse<unknown>>(SECURITY_ACCESS_COMPLIANCE_API_PATHS.complianceControlsMetadata, payload),
  createSacPolicyControlMetadata: (payload: unknown) => apiPost<SacItemResponse<unknown>>(SECURITY_ACCESS_COMPLIANCE_API_PATHS.policyControlsMetadata, payload),
  createSacAuditEventMetadata: (payload: unknown) => apiPost<SacItemResponse<unknown>>(SECURITY_ACCESS_COMPLIANCE_API_PATHS.auditEventsMetadata, payload),
  createSacSensitiveActionReview: (payload: unknown) => apiPost<SacItemResponse<unknown>>(SECURITY_ACCESS_COMPLIANCE_API_PATHS.sensitiveActionsReview, payload),
  createSacDataProtectionEvidence: (payload: unknown) => apiPost<SacItemResponse<unknown>>(SECURITY_ACCESS_COMPLIANCE_API_PATHS.dataProtectionEvidence, payload),
  createSacPrivacyReadinessEvidence: (payload: unknown) => apiPost<SacItemResponse<unknown>>(SECURITY_ACCESS_COMPLIANCE_API_PATHS.privacyReadinessEvidence, payload),
  createSacExceptionMetadata: (payload: unknown) => apiPost<SacItemResponse<unknown>>(SECURITY_ACCESS_COMPLIANCE_API_PATHS.exceptionsMetadata, payload),
  createSacVisitorAccessMetadata: (payload: unknown) => apiPost<SacItemResponse<unknown>>(SECURITY_ACCESS_COMPLIANCE_API_PATHS.visitorAccessMetadata, payload),
  createSacBridgeHr: (payload: unknown) => apiPost<SacItemResponse<unknown>>(SECURITY_ACCESS_COMPLIANCE_API_PATHS.bridgeHr, payload),
  createSacBridgeFinance: (payload: unknown) => apiPost<SacItemResponse<unknown>>(SECURITY_ACCESS_COMPLIANCE_API_PATHS.bridgeFinance, payload),
  createSacBridgeDocuments: (payload: unknown) => apiPost<SacItemResponse<unknown>>(SECURITY_ACCESS_COMPLIANCE_API_PATHS.bridgeDocuments, payload),
  createSacBridgeStudentServices: (payload: unknown) => apiPost<SacItemResponse<unknown>>(SECURITY_ACCESS_COMPLIANCE_API_PATHS.bridgeStudentServices, payload),
  createSacLimitation: (payload: unknown) => apiPost<SacItemResponse<unknown>>(SECURITY_ACCESS_COMPLIANCE_API_PATHS.limitation, payload),
} as const;
