import type { SacRouteKey } from './types';

export const SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS = {
  governanceReadinessEvidenceOnly: 'Governance/readiness/evidence-only security foundation',
  humanReviewRequired: 'Human review required',
  noFakeSecurityCertification: 'No fake security certification',
  noFakeComplianceCertification: 'No fake compliance certification',
  noLegalRegulatoryComplianceClaim: 'No legal/regulatory compliance claim',
  noSocSiemReplacement: 'No SOC/SIEM replacement',
  noFakeIncidentResolution: 'No fake incident resolution',
  noFakeAuditProof: 'No fake audit proof',
  noFakePenetrationTestResult: 'No fake penetration-test result',
  noFakeVulnerabilityScanResult: 'No fake vulnerability-scan result',
  noFakeRiskScore: 'No fake risk score',
  noHiddenUserRiskScore: 'No hidden user risk score',
  noDiscriminatoryRanking: 'No discriminatory ranking',
  noAutonomousEnforcement: 'No autonomous enforcement',
  noAutomaticUserBlocking: 'No automatic user blocking',
  noAutomaticUserSanction: 'No automatic user sanction',
  noAutomaticDataDeletion: 'No automatic data deletion',
  noExternalRegulatorSubmission: 'No external regulator submission',
  noProductionReadySecurityClaim: 'No production-ready security claim',
  incompleteDataSupported: 'Incomplete data supported',
  bridgeFirstReadOnlyFirst: 'Bridge-first / read-only-first',
  noSalesReadyClaim: 'No sales-ready claim',
  noGccReadyClaim: 'No GCC-ready claim',
} as const;

export const SECURITY_ACCESS_COMPLIANCE_NO_OVERCLAIM_COPY = [
  'No fake security certification',
  'No fake compliance certification',
  'No legal/regulatory compliance claim',
  'No SOC/SIEM replacement',
  'No fake audit proof',
  'No fake penetration-test result',
  'No fake vulnerability-scan result',
  'No fake risk score',
  'No hidden user risk score',
  'No discriminatory ranking',
  'No autonomous enforcement',
  'No automatic user blocking',
  'No automatic user sanction',
  'No automatic data deletion',
  'No external regulator submission',
  'No production-ready security claim',
  'No sales-ready claim',
  'No GCC-ready claim',
  'No L5/L6 ready claim.',
] as const;

export const SECURITY_ACCESS_COMPLIANCE_ROUTE_BOUNDARY_LABELS: Record<SacRouteKey, string[]> = {
  overview: [
    SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.governanceReadinessEvidenceOnly,
    SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.humanReviewRequired,
    SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.incompleteDataSupported,
    SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.bridgeFirstReadOnlyFirst,
    SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.noProductionReadySecurityClaim,
    SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.noSalesReadyClaim,
    SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.noGccReadyClaim,
  ],
  dashboard: [
    SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.governanceReadinessEvidenceOnly,
    SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.humanReviewRequired,
    SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.incompleteDataSupported,
    SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.noHiddenUserRiskScore,
    SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.noAutonomousEnforcement,
  ],
  'access-governance': [
    SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.governanceReadinessEvidenceOnly,
    SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.humanReviewRequired,
    SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.noAutonomousEnforcement,
    SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.noAutomaticUserBlocking,
  ],
  'roles-permissions': [
    SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.governanceReadinessEvidenceOnly,
    SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.humanReviewRequired,
    SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.noAutomaticUserBlocking,
  ],
  'rbac-abac': [
    SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.governanceReadinessEvidenceOnly,
    SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.humanReviewRequired,
    SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.noAutonomousEnforcement,
    SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.noHiddenUserRiskScore,
  ],
  sessions: [SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.incompleteDataSupported, SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.humanReviewRequired],
  'login-events': [SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.incompleteDataSupported, SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.humanReviewRequired],
  'mfa-readiness': [SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.humanReviewRequired, SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.noAutonomousEnforcement],
  'tenant-isolation': [SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.humanReviewRequired, SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.noAutonomousEnforcement],
  incidents: [
    SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.humanReviewRequired,
    SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.noFakeIncidentResolution,
    SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.noAutonomousEnforcement,
  ],
  'incident-review': [SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.humanReviewRequired, SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.noFakeIncidentResolution],
  remediation: [SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.humanReviewRequired, SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.noAutonomousEnforcement],
  risks: [SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.humanReviewRequired, SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.noFakeRiskScore],
  'compliance-controls': [SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.humanReviewRequired, SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.noFakeComplianceCertification],
  'policy-controls': [SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.humanReviewRequired, SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.noLegalRegulatoryComplianceClaim],
  'audit-events': [SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.humanReviewRequired, SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.noFakeAuditProof],
  'sensitive-actions': [SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.humanReviewRequired, SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.noAutonomousEnforcement],
  'data-protection': [SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.humanReviewRequired, SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.noFakeVulnerabilityScanResult],
  'privacy-readiness': [SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.humanReviewRequired, SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.noFakePenetrationTestResult],
  exceptions: [SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.humanReviewRequired, SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.noLegalRegulatoryComplianceClaim],
  'visitor-access': [SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.humanReviewRequired, SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.noAutomaticUserBlocking],
  bridges: [SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.bridgeFirstReadOnlyFirst, SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.humanReviewRequired],
  limitations: [SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.incompleteDataSupported, SECURITY_ACCESS_COMPLIANCE_BOUNDARY_LABELS.humanReviewRequired],
};

export function getSacBoundaryLabels(routeKey: SacRouteKey) {
  return SECURITY_ACCESS_COMPLIANCE_ROUTE_BOUNDARY_LABELS[routeKey];
}
