import { apiGet, apiPost } from '@/shared/api/client';
import { CAMPUS_FACILITIES_API_BASE } from './constants';
import type {
  AccessVisitorBridge,
  AuditEvidence,
  AvailabilitySnapshot,
  BuildingRecord,
  CampusFacilitiesApiResult,
  CampusFacilitiesDashboard,
  CampusFacilitiesOverview,
  CampusProfile,
  DormitoryRecord,
  FacilityRecord,
  FinanceAssetBridge,
  FloorRecord,
  HealthResponse,
  HousingRequestMetadata,
  HousingUnit,
  HrStaffBridge,
  Limitations,
  MaintenanceRequest,
  MetadataContract,
  OccupancyVisibility,
  ResponsibleUnit,
  RoomRecord,
  RoomTypeRecord,
  SafetyReadiness,
  ServiceRequest,
  StudentServicesBridge,
  TransportRoute,
  TransportScheduleMetadata,
  TransportVehicleMetadata,
  WorkOrderMetadata,
} from './types';

type ItemResponse<T> = CampusFacilitiesApiResult<{ item: T }>;

function apiPath(path: string) {
  return `${CAMPUS_FACILITIES_API_BASE}${path}`;
}

export const CAMPUS_FACILITIES_API_PATHS = {
  overview: apiPath('/overview'),
  dashboard: apiPath('/dashboard'),
  campus: apiPath('/campus'),
  facilities: apiPath('/facilities'),
  buildings: apiPath('/buildings'),
  floors: apiPath('/floors'),
  rooms: apiPath('/rooms'),
  roomTypes: apiPath('/room-types'),
  availability: apiPath('/availability'),
  occupancy: apiPath('/occupancy'),
  dormitories: apiPath('/dormitories'),
  housingUnits: apiPath('/housing-units'),
  housingRequests: apiPath('/housing-requests'),
  maintenance: apiPath('/maintenance'),
  serviceRequests: apiPath('/service-requests'),
  workOrders: apiPath('/work-orders'),
  transportRoutes: apiPath('/transport/routes'),
  transportVehicles: apiPath('/transport/vehicles'),
  transportSchedules: apiPath('/transport/schedules'),
  responsibleUnits: apiPath('/responsible-units'),
  safetyReadiness: apiPath('/safety-readiness'),
  bridgeAccessVisitor: apiPath('/bridges/access-visitor'),
  bridgeStudentServices: apiPath('/bridges/student-services'),
  bridgeFinanceAsset: apiPath('/bridges/finance-asset'),
  bridgeHrStaff: apiPath('/bridges/hr-staff'),
  auditEvidence: apiPath('/audit-evidence'),
  limitations: apiPath('/limitations'),
  metadataContract: apiPath('/metadata-contract'),
  safetyBoundaries: apiPath('/safety-boundaries'),
  health: apiPath('/health'),
  facilityMetadata: apiPath('/facilities/metadata'),
  buildingMetadata: apiPath('/buildings/metadata'),
  floorMetadata: apiPath('/floors/metadata'),
  roomMetadata: apiPath('/rooms/metadata'),
  availabilityMetadata: apiPath('/availability/metadata'),
  occupancyMetadata: apiPath('/occupancy/metadata'),
  dormitoryMetadata: apiPath('/dormitories/metadata'),
  housingUnitMetadata: apiPath('/housing-units/metadata'),
  housingRequestMetadata: apiPath('/housing-requests/metadata'),
  maintenanceMetadata: apiPath('/maintenance/metadata'),
  serviceRequestMetadata: apiPath('/service-requests/metadata'),
  workOrderMetadata: apiPath('/work-orders/metadata'),
  transportRouteMetadata: apiPath('/transport/routes/metadata'),
  transportVehicleMetadata: apiPath('/transport/vehicles/metadata'),
  transportScheduleMetadata: apiPath('/transport/schedules/metadata'),
  responsibleUnitMetadata: apiPath('/responsible-units/metadata'),
  safetyReadinessEvidence: apiPath('/safety-readiness/evidence'),
  bridgeAccessVisitorMetadata: apiPath('/bridges/access-visitor/metadata'),
  bridgeStudentServicesMetadata: apiPath('/bridges/student-services/metadata'),
  bridgeFinanceAssetMetadata: apiPath('/bridges/finance-asset/metadata'),
  bridgeHrStaffMetadata: apiPath('/bridges/hr-staff/metadata'),
  limitationsMetadata: apiPath('/limitations/metadata'),
} as const;

export const campusFacilitiesApi = {
  getOverview: () => apiGet<CampusFacilitiesOverview>(CAMPUS_FACILITIES_API_PATHS.overview),
  getDashboard: () => apiGet<CampusFacilitiesDashboard>(CAMPUS_FACILITIES_API_PATHS.dashboard),
  getCampus: () => apiGet<CampusProfile>(CAMPUS_FACILITIES_API_PATHS.campus),
  getFacilities: () => apiGet<FacilityRecord>(CAMPUS_FACILITIES_API_PATHS.facilities),
  getBuildings: () => apiGet<BuildingRecord>(CAMPUS_FACILITIES_API_PATHS.buildings),
  getFloors: () => apiGet<FloorRecord>(CAMPUS_FACILITIES_API_PATHS.floors),
  getRooms: () => apiGet<RoomRecord>(CAMPUS_FACILITIES_API_PATHS.rooms),
  getRoomTypes: () => apiGet<RoomTypeRecord>(CAMPUS_FACILITIES_API_PATHS.roomTypes),
  getAvailability: () => apiGet<AvailabilitySnapshot>(CAMPUS_FACILITIES_API_PATHS.availability),
  getOccupancy: () => apiGet<OccupancyVisibility>(CAMPUS_FACILITIES_API_PATHS.occupancy),
  getDormitories: () => apiGet<DormitoryRecord>(CAMPUS_FACILITIES_API_PATHS.dormitories),
  getHousingUnits: () => apiGet<HousingUnit>(CAMPUS_FACILITIES_API_PATHS.housingUnits),
  getHousingRequests: () => apiGet<HousingRequestMetadata>(CAMPUS_FACILITIES_API_PATHS.housingRequests),
  getMaintenance: () => apiGet<MaintenanceRequest>(CAMPUS_FACILITIES_API_PATHS.maintenance),
  getServiceRequests: () => apiGet<ServiceRequest>(CAMPUS_FACILITIES_API_PATHS.serviceRequests),
  getWorkOrders: () => apiGet<WorkOrderMetadata>(CAMPUS_FACILITIES_API_PATHS.workOrders),
  getTransportRoutes: () => apiGet<TransportRoute>(CAMPUS_FACILITIES_API_PATHS.transportRoutes),
  getTransportVehicles: () => apiGet<TransportVehicleMetadata>(CAMPUS_FACILITIES_API_PATHS.transportVehicles),
  getTransportSchedules: () => apiGet<TransportScheduleMetadata>(CAMPUS_FACILITIES_API_PATHS.transportSchedules),
  getResponsibleUnits: () => apiGet<ResponsibleUnit>(CAMPUS_FACILITIES_API_PATHS.responsibleUnits),
  getSafetyReadiness: () => apiGet<SafetyReadiness>(CAMPUS_FACILITIES_API_PATHS.safetyReadiness),
  getAccessVisitorBridge: () => apiGet<AccessVisitorBridge>(CAMPUS_FACILITIES_API_PATHS.bridgeAccessVisitor),
  getStudentServicesBridge: () => apiGet<StudentServicesBridge>(CAMPUS_FACILITIES_API_PATHS.bridgeStudentServices),
  getFinanceAssetBridge: () => apiGet<FinanceAssetBridge>(CAMPUS_FACILITIES_API_PATHS.bridgeFinanceAsset),
  getHrStaffBridge: () => apiGet<HrStaffBridge>(CAMPUS_FACILITIES_API_PATHS.bridgeHrStaff),
  getAuditEvidence: () => apiGet<AuditEvidence>(CAMPUS_FACILITIES_API_PATHS.auditEvidence),
  getLimitations: () => apiGet<Limitations>(CAMPUS_FACILITIES_API_PATHS.limitations),
  getMetadataContract: () => apiGet<MetadataContract>(CAMPUS_FACILITIES_API_PATHS.metadataContract),
  getSafetyBoundaries: () => apiGet<Limitations>(CAMPUS_FACILITIES_API_PATHS.safetyBoundaries),
  getHealth: () => apiGet<HealthResponse>(CAMPUS_FACILITIES_API_PATHS.health),

  submitFacilityMetadata: (payload: unknown) => apiPost<ItemResponse<unknown>>(CAMPUS_FACILITIES_API_PATHS.facilityMetadata, payload),
  submitBuildingMetadata: (payload: unknown) => apiPost<ItemResponse<unknown>>(CAMPUS_FACILITIES_API_PATHS.buildingMetadata, payload),
  submitFloorMetadata: (payload: unknown) => apiPost<ItemResponse<unknown>>(CAMPUS_FACILITIES_API_PATHS.floorMetadata, payload),
  submitRoomMetadata: (payload: unknown) => apiPost<ItemResponse<unknown>>(CAMPUS_FACILITIES_API_PATHS.roomMetadata, payload),
  submitAvailabilityMetadata: (payload: unknown) => apiPost<ItemResponse<unknown>>(CAMPUS_FACILITIES_API_PATHS.availabilityMetadata, payload),
  submitOccupancyMetadata: (payload: unknown) => apiPost<ItemResponse<unknown>>(CAMPUS_FACILITIES_API_PATHS.occupancyMetadata, payload),
  submitDormitoryMetadata: (payload: unknown) => apiPost<ItemResponse<unknown>>(CAMPUS_FACILITIES_API_PATHS.dormitoryMetadata, payload),
  submitHousingUnitMetadata: (payload: unknown) => apiPost<ItemResponse<unknown>>(CAMPUS_FACILITIES_API_PATHS.housingUnitMetadata, payload),
  submitHousingRequestMetadata: (payload: unknown) => apiPost<ItemResponse<unknown>>(CAMPUS_FACILITIES_API_PATHS.housingRequestMetadata, payload),
  submitMaintenanceMetadata: (payload: unknown) => apiPost<ItemResponse<unknown>>(CAMPUS_FACILITIES_API_PATHS.maintenanceMetadata, payload),
  submitServiceRequestMetadata: (payload: unknown) => apiPost<ItemResponse<unknown>>(CAMPUS_FACILITIES_API_PATHS.serviceRequestMetadata, payload),
  submitWorkOrderMetadata: (payload: unknown) => apiPost<ItemResponse<unknown>>(CAMPUS_FACILITIES_API_PATHS.workOrderMetadata, payload),
  submitTransportRouteMetadata: (payload: unknown) => apiPost<ItemResponse<unknown>>(CAMPUS_FACILITIES_API_PATHS.transportRouteMetadata, payload),
  submitTransportVehicleMetadata: (payload: unknown) => apiPost<ItemResponse<unknown>>(CAMPUS_FACILITIES_API_PATHS.transportVehicleMetadata, payload),
  submitTransportScheduleMetadata: (payload: unknown) => apiPost<ItemResponse<unknown>>(CAMPUS_FACILITIES_API_PATHS.transportScheduleMetadata, payload),
  submitResponsibleUnitMetadata: (payload: unknown) => apiPost<ItemResponse<unknown>>(CAMPUS_FACILITIES_API_PATHS.responsibleUnitMetadata, payload),
  submitSafetyReadinessEvidence: (payload: unknown) => apiPost<ItemResponse<unknown>>(CAMPUS_FACILITIES_API_PATHS.safetyReadinessEvidence, payload),
  submitAccessVisitorBridgeMetadata: (payload: unknown) => apiPost<ItemResponse<unknown>>(CAMPUS_FACILITIES_API_PATHS.bridgeAccessVisitorMetadata, payload),
  submitStudentServicesBridgeMetadata: (payload: unknown) => apiPost<ItemResponse<unknown>>(CAMPUS_FACILITIES_API_PATHS.bridgeStudentServicesMetadata, payload),
  submitFinanceAssetBridgeMetadata: (payload: unknown) => apiPost<ItemResponse<unknown>>(CAMPUS_FACILITIES_API_PATHS.bridgeFinanceAssetMetadata, payload),
  submitHrStaffBridgeMetadata: (payload: unknown) => apiPost<ItemResponse<unknown>>(CAMPUS_FACILITIES_API_PATHS.bridgeHrStaffMetadata, payload),
  submitLimitationsMetadata: (payload: unknown) => apiPost<ItemResponse<unknown>>(CAMPUS_FACILITIES_API_PATHS.limitationsMetadata, payload),
} as const;
