services:
  backend:
    restart: always
    environment:
      APP_ENV: production

  frontend:
    restart: always
    environment:
      NODE_ENV: production

  nginx:
    restart: always
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro,Z
      - ./nginx/certs:/etc/nginx/certs:ro,Z
