import { apiGet, apiPatch, apiPost } from '@/shared/api/client';
import { RESEARCH_SCIENCE_API_PATHS } from './constants';
import type {
  ConferenceParticipation,
  ConferenceParticipationCreatePayload,
  ConferenceParticipationUpdatePayload,
  GrantApplication,
  GrantApplicationCreatePayload,
  GrantApplicationUpdatePayload,
  GrantDeliverable,
  GrantDeliverableCreatePayload,
  PublicationMetadata,
  PublicationMetadataCreatePayload,
  PublicationMetadataUpdatePayload,
  ResearchAuditEvent,
  ResearchBridge,
  ResearchBridgeCreatePayload,
  ResearchBridgeSummary,
  ResearchEthicsAmendment,
  ResearchEthicsRequest,
  ResearchEthicsRequestCreatePayload,
  ResearchEthicsRequestUpdatePayload,
  ResearchEvidence,
  ResearchEvidenceCreatePayload,
  ResearchProject,
  ResearchProjectCreatePayload,
  ResearchProjectUpdatePayload,
  ResearchScienceDashboardResponse,
  ResearchScienceHealthResponse,
  ResearchScienceLimitationsResponse,
  ResearchScienceListResponse,
  ResearchScienceMatrixSummaryResponse,
  ScientificSupervision,
  ScientificSupervisionCreatePayload,
  ScientificSupervisionUpdatePayload,
  StudentResearchWork,
  StudentResearchWorkCreatePayload,
  StudentResearchWorkUpdatePayload,
} from './types';

export const researchScienceApi = {
  getResearchScienceHealth: () => apiGet<ResearchScienceHealthResponse>(RESEARCH_SCIENCE_API_PATHS.health),
  getResearchScienceDashboard: () => apiGet<ResearchScienceDashboardResponse>(RESEARCH_SCIENCE_API_PATHS.dashboard),
  getResearchScienceMatrixSummary: () => apiGet<ResearchScienceMatrixSummaryResponse>(RESEARCH_SCIENCE_API_PATHS.matrixSummary),
  getResearchScienceLimitations: () => apiGet<ResearchScienceLimitationsResponse>(RESEARCH_SCIENCE_API_PATHS.limitations),

  listResearchProjects: () => apiGet<ResearchScienceListResponse<ResearchProject>>(RESEARCH_SCIENCE_API_PATHS.projects),
  createResearchProject: (payload: ResearchProjectCreatePayload) => apiPost<ResearchProject>(RESEARCH_SCIENCE_API_PATHS.projects, payload),
  getResearchProject: (id: number | string) => apiGet<ResearchProject>(`${RESEARCH_SCIENCE_API_PATHS.projects}/${id}`),
  updateResearchProject: (id: number | string, payload: ResearchProjectUpdatePayload) => apiPatch<ResearchProject>(`${RESEARCH_SCIENCE_API_PATHS.projects}/${id}`, payload),

  listStudentResearchWork: () => apiGet<ResearchScienceListResponse<StudentResearchWork>>(RESEARCH_SCIENCE_API_PATHS.studentResearch),
  createStudentResearchWork: (payload: StudentResearchWorkCreatePayload) => apiPost<StudentResearchWork>(RESEARCH_SCIENCE_API_PATHS.studentResearch, payload),
  getStudentResearchWork: (id: number | string) => apiGet<StudentResearchWork>(`${RESEARCH_SCIENCE_API_PATHS.studentResearch}/${id}`),
  updateStudentResearchWork: (id: number | string, payload: StudentResearchWorkUpdatePayload) => apiPatch<StudentResearchWork>(`${RESEARCH_SCIENCE_API_PATHS.studentResearch}/${id}`, payload),

  listScientificSupervision: () => apiGet<ResearchScienceListResponse<ScientificSupervision>>(RESEARCH_SCIENCE_API_PATHS.supervision),
  createScientificSupervision: (payload: ScientificSupervisionCreatePayload) => apiPost<ScientificSupervision>(RESEARCH_SCIENCE_API_PATHS.supervision, payload),
  getScientificSupervision: (id: number | string) => apiGet<ScientificSupervision>(`${RESEARCH_SCIENCE_API_PATHS.supervision}/${id}`),
  updateScientificSupervision: (id: number | string, payload: ScientificSupervisionUpdatePayload) => apiPatch<ScientificSupervision>(`${RESEARCH_SCIENCE_API_PATHS.supervision}/${id}`, payload),

  listPublications: () => apiGet<ResearchScienceListResponse<PublicationMetadata>>(RESEARCH_SCIENCE_API_PATHS.publications),
  createPublicationMetadata: (payload: PublicationMetadataCreatePayload) => apiPost<PublicationMetadata>(RESEARCH_SCIENCE_API_PATHS.publications, payload),
  getPublicationMetadata: (id: number | string) => apiGet<PublicationMetadata>(`${RESEARCH_SCIENCE_API_PATHS.publications}/${id}`),
  updatePublicationMetadata: (id: number | string, payload: PublicationMetadataUpdatePayload) => apiPatch<PublicationMetadata>(`${RESEARCH_SCIENCE_API_PATHS.publications}/${id}`, payload),

  listConferences: () => apiGet<ResearchScienceListResponse<ConferenceParticipation>>(RESEARCH_SCIENCE_API_PATHS.conferences),
  createConferenceParticipation: (payload: ConferenceParticipationCreatePayload) => apiPost<ConferenceParticipation>(RESEARCH_SCIENCE_API_PATHS.conferences, payload),
  getConferenceParticipation: (id: number | string) => apiGet<ConferenceParticipation>(`${RESEARCH_SCIENCE_API_PATHS.conferences}/${id}`),
  updateConferenceParticipation: (id: number | string, payload: ConferenceParticipationUpdatePayload) => apiPatch<ConferenceParticipation>(`${RESEARCH_SCIENCE_API_PATHS.conferences}/${id}`, payload),

  listGrants: () => apiGet<ResearchScienceListResponse<GrantApplication>>(RESEARCH_SCIENCE_API_PATHS.grants),
  createGrantApplication: (payload: GrantApplicationCreatePayload) => apiPost<GrantApplication>(RESEARCH_SCIENCE_API_PATHS.grants, payload),
  getGrantApplication: (id: number | string) => apiGet<GrantApplication>(`${RESEARCH_SCIENCE_API_PATHS.grants}/${id}`),
  updateGrantApplication: (id: number | string, payload: GrantApplicationUpdatePayload) => apiPatch<GrantApplication>(`${RESEARCH_SCIENCE_API_PATHS.grants}/${id}`, payload),
  listGrantDeliverables: () => apiGet<ResearchScienceListResponse<GrantDeliverable>>(RESEARCH_SCIENCE_API_PATHS.grantDeliverables),
  createGrantDeliverable: (payload: GrantDeliverableCreatePayload) => apiPost<GrantDeliverable>(RESEARCH_SCIENCE_API_PATHS.grantDeliverables, payload),
  updateGrantDeliverable: (id: number | string, payload: Partial<GrantDeliverableCreatePayload>) => apiPatch<GrantDeliverable>(`${RESEARCH_SCIENCE_API_PATHS.grantDeliverables}/${id}`, payload),

  listEthicsRequests: () => apiGet<ResearchScienceListResponse<ResearchEthicsRequest>>(RESEARCH_SCIENCE_API_PATHS.ethics),
  createEthicsRequest: (payload: ResearchEthicsRequestCreatePayload) => apiPost<ResearchEthicsRequest>(RESEARCH_SCIENCE_API_PATHS.ethics, payload),
  getEthicsRequest: (id: number | string) => apiGet<ResearchEthicsRequest>(`${RESEARCH_SCIENCE_API_PATHS.ethics}/${id}`),
  updateEthicsRequest: (id: number | string, payload: ResearchEthicsRequestUpdatePayload) => apiPatch<ResearchEthicsRequest>(`${RESEARCH_SCIENCE_API_PATHS.ethics}/${id}`, payload),
  listEthicsAmendments: () => apiGet<ResearchScienceListResponse<ResearchEthicsAmendment>>(RESEARCH_SCIENCE_API_PATHS.ethicsAmendments),
  createEthicsAmendment: (payload: Partial<ResearchEthicsAmendment> & { amendment_ref: string; title: string }) => apiPost<ResearchEthicsAmendment>(RESEARCH_SCIENCE_API_PATHS.ethicsAmendments, payload),

  listResearchEvidence: () => apiGet<ResearchScienceListResponse<ResearchEvidence>>(RESEARCH_SCIENCE_API_PATHS.evidence),
  attachResearchEvidence: (payload: ResearchEvidenceCreatePayload) => apiPost<ResearchEvidence>(RESEARCH_SCIENCE_API_PATHS.evidence, payload),
  listResearchAuditEvents: () => apiGet<ResearchScienceListResponse<ResearchAuditEvent>>(RESEARCH_SCIENCE_API_PATHS.audit),
  listResearchBridges: () => apiGet<ResearchScienceListResponse<ResearchBridge>>(RESEARCH_SCIENCE_API_PATHS.bridges),
  createResearchBridge: (payload: ResearchBridgeCreatePayload) => apiPost<ResearchBridge>(RESEARCH_SCIENCE_API_PATHS.bridges, payload),
  getResearchBridgeSummary: () => apiGet<ResearchBridgeSummary>(RESEARCH_SCIENCE_API_PATHS.bridgesSummary),
};