import { apiGet } from '@/shared/api/client';
import { COMMUNICATIONS_API_PATHS } from './constants';
import type {
  AnnouncementListResponse,
  AnnouncementRegistrySummaryResponse,
  BrainActionBoundaryItem,
  CommDomainSummary,
  CommunicationsRuntimeShellResponse,
  DeliveryAuditBoundary,
  DeliveryAuditListResponse,
  DeliveryAuditSummaryResponse,
  EscalationWorkflowBoundary,
  EscalationWorkflowListResponse,
  EscalationWorkflowSummaryResponse,
  MessageTemplateListResponse,
  MessageTemplateRegistryBoundary,
  MessageTemplateRegistrySummaryResponse,
  NotificationCenterSummaryResponse,
  NotificationListResponse,
  NotificationPreferenceListResponse,
  NotificationPreferenceRegistryBoundary,
  NotificationPreferenceRegistrySummaryResponse,
  NotificationProviderBoundary,
  ProviderReadinessSummary,
  AnnouncementRegistryBoundary,
} from './types';

export const communicationsApi = {
  getOverview: () => apiGet<CommunicationsRuntimeShellResponse>(COMMUNICATIONS_API_PATHS.overview),
  getDomains: () => apiGet<{ tenant_id: number; total_domains: number; total_planned_tables: number; domains: CommDomainSummary[] }>(COMMUNICATIONS_API_PATHS.domains),
  getProviderReadiness: () => apiGet<{ tenant_id: number; status_label: string; live_delivery_enabled: boolean; providers: ProviderReadinessSummary[] }>(COMMUNICATIONS_API_PATHS.providerReadiness),
  getBrainActions: () => apiGet<{ tenant_id: number; brain_action_boundary: string; samples: BrainActionBoundaryItem[] }>(COMMUNICATIONS_API_PATHS.brainActions),
  getNotifications: () => apiGet<NotificationListResponse>(COMMUNICATIONS_API_PATHS.notifications),
  getNotificationsSummary: () => apiGet<NotificationCenterSummaryResponse>(COMMUNICATIONS_API_PATHS.notificationsSummary),
  getNotificationsBoundary: () => apiGet<NotificationProviderBoundary>(COMMUNICATIONS_API_PATHS.notificationsBoundary),
  getAnnouncements: () => apiGet<AnnouncementListResponse>(COMMUNICATIONS_API_PATHS.announcements),
  getAnnouncementsSummary: () => apiGet<AnnouncementRegistrySummaryResponse>(COMMUNICATIONS_API_PATHS.announcementsSummary),
  getAnnouncementsBoundary: () => apiGet<AnnouncementRegistryBoundary>(COMMUNICATIONS_API_PATHS.announcementsBoundary),
  getTemplates: () => apiGet<MessageTemplateListResponse>(COMMUNICATIONS_API_PATHS.templates),
  getTemplatesSummary: () => apiGet<MessageTemplateRegistrySummaryResponse>(COMMUNICATIONS_API_PATHS.templatesSummary),
  getTemplatesBoundary: () => apiGet<MessageTemplateRegistryBoundary>(COMMUNICATIONS_API_PATHS.templatesBoundary),
  getPreferences: () => apiGet<NotificationPreferenceListResponse>(COMMUNICATIONS_API_PATHS.preferences),
  getPreferencesSummary: () => apiGet<NotificationPreferenceRegistrySummaryResponse>(COMMUNICATIONS_API_PATHS.preferencesSummary),
  getPreferencesBoundary: () => apiGet<NotificationPreferenceRegistryBoundary>(COMMUNICATIONS_API_PATHS.preferencesBoundary),
  getDeliveryAudit: () => apiGet<DeliveryAuditListResponse>(COMMUNICATIONS_API_PATHS.deliveryAudit),
  getDeliveryAuditSummary: () => apiGet<DeliveryAuditSummaryResponse>(COMMUNICATIONS_API_PATHS.deliveryAuditSummary),
  getDeliveryAuditBoundary: () => apiGet<DeliveryAuditBoundary>(COMMUNICATIONS_API_PATHS.deliveryAuditBoundary),
  getEscalations: () => apiGet<EscalationWorkflowListResponse>(COMMUNICATIONS_API_PATHS.escalations),
  getEscalationsSummary: () => apiGet<EscalationWorkflowSummaryResponse>(COMMUNICATIONS_API_PATHS.escalationsSummary),
  getEscalationsBoundary: () => apiGet<EscalationWorkflowBoundary>(COMMUNICATIONS_API_PATHS.escalationsBoundary),
};
