import { PERMISSIONS } from '@/shared/config/permissions';

export const EXECUTIVE_CONTROL_TOWER_PERMISSIONS = {
  READ: PERMISSIONS.EXECUTIVE_CONTROL_TOWER_READ,
  SUMMARY_READ: PERMISSIONS.EXECUTIVE_CONTROL_TOWER_SUMMARY_READ,
  ASSIGNMENTS_READ: PERMISSIONS.EXECUTIVE_CONTROL_TOWER_ASSIGNMENTS_READ,
  DOCUMENTS_READ: PERMISSIONS.EXECUTIVE_CONTROL_TOWER_DOCUMENTS_READ,
  SLA_RISK_READ: PERMISSIONS.EXECUTIVE_CONTROL_TOWER_SLA_RISK_READ,
  STRATEGY_READ: PERMISSIONS.EXECUTIVE_CONTROL_TOWER_STRATEGY_READ,
  AUDIT_READ: PERMISSIONS.EXECUTIVE_CONTROL_TOWER_AUDIT_READ,
  DEPARTMENT_READ: PERMISSIONS.EXECUTIVE_CONTROL_TOWER_DEPARTMENT_READ,
  METRIC_REGISTRY_READ: PERMISSIONS.EXECUTIVE_CONTROL_TOWER_METRIC_REGISTRY_READ,
} as const;

export const EXECUTIVE_CONTROL_TOWER_READ_PERMISSIONS = [
  EXECUTIVE_CONTROL_TOWER_PERMISSIONS.READ,
  EXECUTIVE_CONTROL_TOWER_PERMISSIONS.SUMMARY_READ,
  EXECUTIVE_CONTROL_TOWER_PERMISSIONS.ASSIGNMENTS_READ,
  EXECUTIVE_CONTROL_TOWER_PERMISSIONS.DOCUMENTS_READ,
  EXECUTIVE_CONTROL_TOWER_PERMISSIONS.SLA_RISK_READ,
  EXECUTIVE_CONTROL_TOWER_PERMISSIONS.STRATEGY_READ,
  EXECUTIVE_CONTROL_TOWER_PERMISSIONS.AUDIT_READ,
  EXECUTIVE_CONTROL_TOWER_PERMISSIONS.DEPARTMENT_READ,
  EXECUTIVE_CONTROL_TOWER_PERMISSIONS.METRIC_REGISTRY_READ,
] as const;

export const EXECUTIVE_CONTROL_TOWER_SECTION_PERMISSIONS = {
  overview: EXECUTIVE_CONTROL_TOWER_PERMISSIONS.SUMMARY_READ,
  assignments: EXECUTIVE_CONTROL_TOWER_PERMISSIONS.ASSIGNMENTS_READ,
  documents: EXECUTIVE_CONTROL_TOWER_PERMISSIONS.DOCUMENTS_READ,
  decrees: EXECUTIVE_CONTROL_TOWER_PERMISSIONS.DOCUMENTS_READ,
  correspondence: EXECUTIVE_CONTROL_TOWER_PERMISSIONS.DOCUMENTS_READ,
  slaRisk: EXECUTIVE_CONTROL_TOWER_PERMISSIONS.SLA_RISK_READ,
  strategy: EXECUTIVE_CONTROL_TOWER_PERMISSIONS.STRATEGY_READ,
  audit: EXECUTIVE_CONTROL_TOWER_PERMISSIONS.AUDIT_READ,
  departments: EXECUTIVE_CONTROL_TOWER_PERMISSIONS.DEPARTMENT_READ,
  metricRegistry: EXECUTIVE_CONTROL_TOWER_PERMISSIONS.METRIC_REGISTRY_READ,
  health: EXECUTIVE_CONTROL_TOWER_PERMISSIONS.READ,
} as const;