import { apiGet } from '@/shared/api/client';
import type {
  DevelopmentProgramSummary,
  ExecutiveAssignmentEntry,
  ExecutiveAssignmentSummary,
  ExecutiveControlTowerSummary,
  ExecutiveDecisionExecutionSummary,
  ExecutiveDecisionRegistryEntry,
  ExecutiveDecisionRegistrySummary,
  ExecutiveExecutionMetrics,
  ExecutiveGovernanceDashboardSummary,
  ExecutiveKpiOverview,
  ExecutiveKpiEntry,
  ExecutiveKpiRiskCenter,
  ExecutiveKpiSummary,
  ExecutiveKpiTrendSummary,
  ExecutiveMeetingEntry,
  ExecutiveMeetingSummary,
  ExecutivePerformanceMetrics,
  ExecutiveProtocolEntry,
  ExecutiveProtocolExecutionSummary,
  ExecutiveProtocolSummary,
  ExecutiveRiskOverview,
  PerformanceGovernanceSummary,
  RectorDashboardRuntimeSummary,
  StrategicInitiativeEntry,
  StrategicInitiativeMetrics,
  StrategicInitiativeSummary,
  ExecutiveGovernanceRuntimeOverview,
  ExecutiveGovernanceRuntimeSummary,
  ExecutiveGovernanceSignalSummary,
} from './types';

const BASE = '/api/admin/executive-governance/runtime';

export const executiveGovernanceApi = {
  getOverview: () => apiGet<ExecutiveGovernanceRuntimeOverview>(`${BASE}/overview`),
  getSummary: () => apiGet<ExecutiveGovernanceRuntimeSummary>(`${BASE}/summary`),
  getSignals: () => apiGet<ExecutiveGovernanceSignalSummary[]>(`${BASE}/signals`),
  getDashboard: () => apiGet<ExecutiveGovernanceDashboardSummary>(`${BASE}/dashboard`),
  getDecisions: () => apiGet<ExecutiveDecisionRegistryEntry[]>(`${BASE}/decisions`),
  getDecisionSummary: () => apiGet<ExecutiveDecisionRegistrySummary>(`${BASE}/decisions/summary`),
  getDecisionExecution: () => apiGet<ExecutiveDecisionExecutionSummary>(`${BASE}/decisions/execution`),
  getAssignments: () => apiGet<ExecutiveAssignmentEntry[]>(`${BASE}/assignments`),
  getAssignmentSummary: () => apiGet<ExecutiveAssignmentSummary>(`${BASE}/assignments/summary`),
  getAssignmentExecution: () => apiGet<ExecutiveExecutionMetrics>(`${BASE}/assignments/execution`),
  getAssignmentRisks: () => apiGet<ExecutiveExecutionMetrics>(`${BASE}/assignments/risks`),
  getControlTower: () => apiGet<ExecutiveControlTowerSummary>(`${BASE}/control-tower`),
  getControlTowerSummary: () => apiGet<RectorDashboardRuntimeSummary>(`${BASE}/control-tower/summary`),
  getControlTowerRisks: () => apiGet<ExecutiveRiskOverview>(`${BASE}/control-tower/risks`),
  getControlTowerKpis: () => apiGet<ExecutiveKpiOverview>(`${BASE}/control-tower/kpis`),
  getControlTowerEscalations: () => apiGet<ExecutivePerformanceMetrics>(`${BASE}/control-tower/escalations`),
  getKpis: () => apiGet<ExecutiveKpiEntry[]>(`${BASE}/kpis`),
  getKpiSummary: () => apiGet<ExecutiveKpiSummary>(`${BASE}/kpis/summary`),
  getKpiPerformance: () => apiGet<PerformanceGovernanceSummary>(`${BASE}/kpis/performance`),
  getKpiRisks: () => apiGet<ExecutiveKpiRiskCenter>(`${BASE}/kpis/risks`),
  getKpiTrends: () => apiGet<ExecutiveKpiTrendSummary>(`${BASE}/kpis/trends`),
  getStrategicInitiatives: () => apiGet<StrategicInitiativeEntry[]>(`${BASE}/strategic-initiatives`),
  getStrategicInitiativesSummary: () => apiGet<StrategicInitiativeSummary>(`${BASE}/strategic-initiatives/summary`),
  getStrategicInitiativesRisks: () => apiGet<StrategicInitiativeMetrics>(`${BASE}/strategic-initiatives/risks`),
  getDevelopmentProgram: () => apiGet<DevelopmentProgramSummary>(`${BASE}/development-program`),
  getDevelopmentProgramSummary: () => apiGet<DevelopmentProgramSummary>(`${BASE}/development-program/summary`),
  getMeetings: () => apiGet<ExecutiveMeetingEntry[]>(`${BASE}/meetings`),
  getMeetingSummary: () => apiGet<ExecutiveMeetingSummary>(`${BASE}/meetings/summary`),
  getProtocols: () => apiGet<ExecutiveProtocolEntry[]>(`${BASE}/protocols`),
  getProtocolSummary: () => apiGet<ExecutiveProtocolSummary>(`${BASE}/protocols/summary`),
  getProtocolExecution: () => apiGet<ExecutiveProtocolExecutionSummary>(`${BASE}/protocols/execution`),
};
