"use client";

import Link from "next/link";
import { useState } from "react";
import { PageHeader } from "@/shared/ui/page-header";
import { Skeleton } from "@/shared/ui/skeleton";
import { ErrorState } from "@/shared/ui/error-state";
import { Button } from "@/shared/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/shared/ui/card";
import { useMutationFeedback } from "@/shared/hooks/use-mutation-feedback";
import { AccessDenied, PermissionGate } from "@/shared/ui/permission-gate";
import { PERMISSIONS } from "@/shared/config/permissions";
import { usePermissions } from "@/shared/hooks/use-permissions";
import { useCreateTranscriptSnapshot, useTranscript } from "@/modules/transcripts/hooks";
import type { TranscriptSnapshot } from "@/modules/transcripts/types";
import { formatDate } from "@/shared/utils/format";
import { FileText, ChevronLeft } from "lucide-react";

export default function TranscriptPage({ params }: { params: { id: string } }) {
  const { id } = params;
  const { hasPermission } = usePermissions();
  const { data: transcript, isLoading, error, refetch } = useTranscript(id);
  const [lastSnapshot, setLastSnapshot] = useState<TranscriptSnapshot | null>(null);
  const { getHandlers } = useMutationFeedback();
  const createSnapshot = useCreateTranscriptSnapshot(id);

  if (!hasPermission(PERMISSIONS.TRANSCRIPTS_READ)) return <AccessDenied />;

  if (isLoading) {
    return (
      <div className="space-y-4">
        <Skeleton className="h-16 rounded-lg" />
        <Skeleton className="h-64 rounded-lg" />
      </div>
    );
  }
  if (error || !transcript) return <ErrorState title="Transcript not found" onRetry={refetch} />;

  return (
    <div className="space-y-6 max-w-3xl">
      <div className="flex items-center gap-3">
        <Link href={`/console/students/${id}`}>
          <Button variant="ghost" size="sm">
            <ChevronLeft className="h-4 w-4" />
          </Button>
        </Link>
        <PageHeader
          title="Transcript"
          description={`${transcript.student_name} · ${transcript.student_number}`}
          icon={FileText}
          actions={
            <PermissionGate permission={PERMISSIONS.TRANSCRIPTS_WRITE}>
              <Button
                onClick={() => {
                  const feedback = getHandlers<TranscriptSnapshot>({
                    successTitle: "Transcript snapshot created",
                    successDescription: (snapshot) => `Snapshot #${snapshot.id} created ${formatDate(snapshot.generated_at)}.`,
                    errorTitle: "Unable to create transcript snapshot",
                  });

                  createSnapshot.mutate(undefined, {
                    onSuccess: (snapshot) => {
                      feedback.onSuccess(snapshot);
                      setLastSnapshot(snapshot);
                    },
                    onError: feedback.onError,
                  });
                }}
                disabled={createSnapshot.isPending}
              >
                {createSnapshot.isPending ? "Creating..." : "Create snapshot"}
              </Button>
            </PermissionGate>
          }
        />
      </div>

      {lastSnapshot ? (
        <Card>
          <CardHeader>
            <CardTitle className="text-base">Latest snapshot</CardTitle>
            <CardDescription>Immutable transcript export created for audit and registrar workflows.</CardDescription>
          </CardHeader>
          <CardContent className="grid gap-2 text-sm sm:grid-cols-3">
            <div>
              <p className="text-xs text-muted-foreground">Snapshot ID</p>
              <p className="font-medium">#{lastSnapshot.id}</p>
            </div>
            <div>
              <p className="text-xs text-muted-foreground">Generated by</p>
              <p className="font-medium">{lastSnapshot.generated_by}</p>
            </div>
            <div>
              <p className="text-xs text-muted-foreground">Generated at</p>
              <p className="font-medium">{formatDate(lastSnapshot.generated_at)}</p>
            </div>
          </CardContent>
        </Card>
      ) : null}

      <div className="grid gap-3 sm:grid-cols-3 text-sm">
        <div className="rounded-lg border bg-card p-3">
          <p className="text-xs text-muted-foreground">GPA</p>
          <p className="font-semibold text-lg">{transcript.gpa?.toFixed(2) ?? "—"}</p>
        </div>
        <div className="rounded-lg border bg-card p-3">
          <p className="text-xs text-muted-foreground">Credits</p>
          <p className="font-semibold text-lg">{transcript.total_credits}</p>
        </div>
        <div className="rounded-lg border bg-card p-3">
          <p className="text-xs text-muted-foreground">Program</p>
          <p className="font-semibold text-sm">{transcript.program ?? "—"}</p>
        </div>
      </div>

      <div className="rounded-lg border bg-card overflow-hidden">
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b bg-muted/50">
              <th className="px-4 py-2 text-left font-medium">Course</th>
              <th className="px-4 py-2 text-left font-medium">Section</th>
              <th className="px-4 py-2 text-left font-medium">Semester</th>
              <th className="px-4 py-2 text-center font-medium">Credits</th>
              <th className="px-4 py-2 text-center font-medium">Grade</th>
            </tr>
          </thead>
          <tbody className="divide-y">
            {transcript.entries.map((e, i) => (
              <tr key={i} className={e.completed ? "" : "text-muted-foreground"}>
                <td className="px-4 py-2">{e.course_name}</td>
                <td className="px-4 py-2">
                  <code className="text-xs">{e.section_code}</code>
                </td>
                <td className="px-4 py-2">{e.semester}</td>
                <td className="px-4 py-2 text-center">{e.credits}</td>
                <td className="px-4 py-2 text-center font-medium">{e.grade_value ?? "—"}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <p className="text-xs text-muted-foreground">Generated {formatDate(transcript.generated_at)}</p>
    </div>
  );
}
