#!/usr/bin/env bash
# F1.10 Final DoD Sign-off
# Prerequisites: F1.9_GATE=PASS (all due official day-1/day-3/day-7 reviews complete)
# Usage: bash scripts/f1_risk_dod_signoff.sh
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COMPOSE=(docker compose -f "${ROOT_DIR}/infra/docker-compose.yml" --env-file "${ROOT_DIR}/infra/.env")
ARTIFACTS_DIR="${ROOT_DIR}/docs/runbooks/artifacts"
STAMP="$(date -u +%Y%m%d_%H%M%S)"
OUT_FILE="${ARTIFACTS_DIR}/f1_risk_dod_signoff_${STAMP}.md"

bash "${ROOT_DIR}/scripts/docker_only_guard.sh"
mkdir -p "${ARTIFACTS_DIR}"

# --- Gate check ---
echo "[f1-dod] Checking F1.9 gate..."
gate_output="$(bash "${ROOT_DIR}/scripts/risk_phase_f1_post_release_gate.sh" 2>&1 || true)"
gate_status="$(echo "${gate_output}" | awk -F= '$1=="F1.9_GATE"{print $2}')"

if [[ "${gate_status}" != "PASS" ]]; then
  echo "[f1-dod] BLOCKED: F1.9_GATE=${gate_status:-UNKNOWN}"
  echo "${gate_output}"
  echo "[f1-dod] Complete all due official day-1/day-3/day-7 reviews before sign-off."
  exit 1
fi

echo "[f1-dod] F1.9 gate PASS — proceeding to verification..."

# Extract review artifacts from gate output
parse_gate() {
  echo "${gate_output}" | awk -F= -v k="$1" '$1==k{print $2}'
}
day0_baseline="$(parse_gate "DAY0_BASELINE")"
day1_artifact="$(parse_gate "DAY1_ARTIFACT")"
day3_artifact="$(parse_gate "DAY3_ARTIFACT")"
day7_artifact="$(parse_gate "DAY7_ARTIFACT")"

# --- Final verification bundle ---
echo "[f1-dod] Running final verification bundle..."
pushd "${ROOT_DIR}/infra" >/dev/null
BACKEND_TEST_OUTPUT="$("${COMPOSE[@]}" run --rm --no-deps -e DATABASE_URL= backend-tests pytest -q \
  tests/modules/interventions/test_risk_observability_metrics.py \
  tests/modules/interventions/test_router_interventions_risk_phasec.py::test_run_risk_detection_success \
  tests/test_rate_limit.py::test_sensitive_admin_rate_limit_returns_429_and_audits \
  tests/test_feature_flags_tenant_isolation.py::test_feature_flag_mutation_is_audited \
  --no-cov -rA 2>&1)"

PROMTOOL_OUTPUT="$("${COMPOSE[@]}" run --rm --no-deps --entrypoint promtool prometheus check rules /etc/prometheus/alerts.yml 2>&1)"
popd >/dev/null

SIGNED_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

cat >"${OUT_FILE}" <<EOF
# F1 AI Early-Warning Engine — Final DoD Sign-off

- Signed at (UTC): ${SIGNED_AT}
- F1.9 gate: PASS
- Signed by: automated sign-off script

## Review Artifacts

- Day-0 baseline: ${day0_baseline}
- Day-1 review: ${day1_artifact}
- Day-3 review: ${day3_artifact}
- Day-7 review: ${day7_artifact}

## Final Verification Bundle

### Backend checks

\`\`\`text
${BACKEND_TEST_OUTPUT}
\`\`\`

### Prometheus rules validation

\`\`\`text
${PROMTOOL_OUTPUT}
\`\`\`

## DoD Checklist

| # | Criterion | Status |
|---|-----------|--------|
| F1.1 | Product Contract + KPI baseline | ✅ DONE |
| F1.2 | Domain/Data design (schema + migrations) | ✅ DONE |
| F1.3 | Backend delivery (risk engine + API) | ✅ DONE |
| F1.4 | Frontend delivery (risk dashboard + advisor UI) | ✅ DONE |
| F1.5 | Observability/SRE (metrics/alerts/SLO/runbook) | ✅ DONE |
| F1.6 | Security/compliance (tenant isolation + abuse + audit) | ✅ DONE |
| F1.7 | Testing matrix full pass | ✅ DONE |
| F1.8 | Release/adoption + rollback (feature flag gate) | ✅ DONE |
| F1.9 | Post-release validation day-1/day-3/day-7 reviews | ✅ DONE (gate PASS) |
| F1.10 | Final DoD sign-off | ✅ DONE (this artifact) |

## Verdict

**F1 AI Early-Warning Engine: DEFINITION OF DONE COMPLETE**

Feature flag: \`risk.early_warning_engine\`
Post-release state: stable, all KPI reviews passed
Tenant isolation: verified
Next feature: F2 Auto Intervention Playbooks (parallel track, already in progress)

## Notes

- Generated by: scripts/f1_risk_dod_signoff.sh
- Gate prerequisite: all due official day-1/day-3/day-7 reviews present and non-early
- F1.10 unlocks: F2.10 parallel sign-off + F3 start eligibility
EOF

echo "[f1-dod] Sign-off artifact created: ${OUT_FILE}"
echo "F1.10_STATUS=DONE"
echo "ARTIFACT=${OUT_FILE##*/}"
