#!/usr/bin/env bash
# F2.10 Final DoD Sign-off
# Prerequisites: F2.9_GATE=PASS (all official day-1/day-3/day-7 reviews complete)
# Usage: bash scripts/f2_playbooks_dod_signoff.sh
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COMPOSE=(docker compose -f "${ROOT_DIR}/infra/docker-compose.yml" --env-file "${ROOT_DIR}/infra/.env")
ARTIFACTS_DIR="${ROOT_DIR}/docs/runbooks/artifacts"
STAMP="$(date -u +%Y%m%d_%H%M%S)"
OUT_FILE="${ARTIFACTS_DIR}/f2_playbooks_dod_signoff_${STAMP}.md"

bash "${ROOT_DIR}/scripts/docker_only_guard.sh"
mkdir -p "${ARTIFACTS_DIR}"

# --- Gate check ---
echo "[f2-dod] Checking F2.9 gate..."
gate_output="$(bash "${ROOT_DIR}/scripts/f2_playbooks_post_release_gate.sh" 2>&1 || true)"
gate_status="$(echo "${gate_output}" | awk -F= '$1=="F2.9_GATE"{print $2}')"

if [[ "${gate_status}" != "PASS" ]]; then
  echo "[f2-dod] BLOCKED: F2.9_GATE=${gate_status:-UNKNOWN}"
  echo "${gate_output}"
  echo "[f2-dod] Complete all official day-1/day-3/day-7 reviews before sign-off."
  exit 1
fi

echo "[f2-dod] F2.9 gate PASS — proceeding to verification..."

parse_gate() {
  echo "${gate_output}" | awk -F= -v k="$1" '$1==k{print $2}'
}
day0_baseline="$(parse_gate "DAY0_BASELINE")"
day1_artifact="$(parse_gate "DAY1_ARTIFACT")"
day3_artifact="$(parse_gate "DAY3_ARTIFACT")"
day7_artifact="$(parse_gate "DAY7_ARTIFACT")"

# --- Final verification bundle ---
echo "[f2-dod] Running final verification bundle..."
pushd "${ROOT_DIR}/infra" >/dev/null
BACKEND_TEST_OUTPUT="$("${COMPOSE[@]}" run --rm --no-deps -e DATABASE_URL= backend-tests pytest -q \
  tests/modules/interventions/test_router_playbooks_phase2.py \
  tests/modules/interventions/test_playbook_security_guards.py \
  tests/modules/interventions/test_risk_observability_metrics.py \
  --no-cov -rA 2>&1)"

PROMTOOL_OUTPUT="$("${COMPOSE[@]}" run --rm --no-deps --entrypoint promtool prometheus check rules /etc/prometheus/alerts.yml 2>&1)"
popd >/dev/null

SIGNED_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

cat >"${OUT_FILE}" <<EOF
# F2 Auto Intervention Playbooks — Final DoD Sign-off

- Signed at (UTC): ${SIGNED_AT}
- F2.9 gate: PASS
- Signed by: automated sign-off script

## Review Artifacts

- Day-0 baseline: ${day0_baseline}
- Day-1 review: ${day1_artifact}
- Day-3 review: ${day3_artifact}
- Day-7 review: ${day7_artifact}

## Final Verification Bundle

### Backend checks

\`\`\`text
${BACKEND_TEST_OUTPUT}
\`\`\`

### Prometheus rules validation

\`\`\`text
${PROMTOOL_OUTPUT}
\`\`\`

## DoD Checklist

| # | Criterion | Status |
|---|-----------|--------|
| F2.1 | Product Contract + KPI baseline | ✅ DONE |
| F2.2 | Domain/Data design (schema + migrations) | ✅ DONE |
| F2.3 | Backend delivery (playbook engine + API) | ✅ DONE |
| F2.4 | Frontend delivery (playbook builder + execution UI) | ✅ DONE |
| F2.5 | Observability/SRE (metrics/alerts/SLO/runbook) | ✅ DONE |
| F2.6 | Security/compliance (tenant isolation + abuse + audit) | ✅ DONE |
| F2.7 | Testing matrix full pass | ✅ DONE |
| F2.8 | Release/adoption + rollback (feature flag gate) | ✅ DONE |
| F2.9 | Post-release validation day-1/day-3/day-7 reviews | ✅ DONE (gate PASS) |
| F2.10 | Final DoD sign-off | ✅ DONE (this artifact) |

## Verdict

**F2 Auto Intervention Playbooks: DEFINITION OF DONE COMPLETE**

Feature flag: \`interventions.auto_playbooks\`
Post-release state: stable, all KPI reviews passed
Tenant isolation: verified
Next feature: F3 Intervention Effectiveness Lab

## Notes

- Generated by: scripts/f2_playbooks_dod_signoff.sh
- Gate prerequisite: all official day-1/day-3/day-7 reviews present and non-early
- F2.10 unlocks: F3 Intervention Effectiveness Lab start eligibility
EOF

echo "[f2-dod] Sign-off artifact created: ${OUT_FILE}"
echo "F2.10_STATUS=DONE"
echo "ARTIFACT=${OUT_FILE##*/}"
