#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COMPOSE=(docker compose --env-file .env)
ARTIFACTS_DIR="${ROOT_DIR}/docs/runbooks/artifacts"
STAMP="$(date -u +%Y%m%d_%H%M%S)"
OUT_FILE="${ARTIFACTS_DIR}/f2_playbooks_day0_baseline_${STAMP}.md"

bash "${ROOT_DIR}/scripts/docker_only_guard.sh"
mkdir -p "${ARTIFACTS_DIR}"

pushd "${ROOT_DIR}/infra" >/dev/null

BACKEND_TEST_OUTPUT="$(${COMPOSE[@]} run --rm --no-deps -e DATABASE_URL= backend-tests pytest -q \
  tests/modules/interventions/test_router_playbooks_phase2.py \
  tests/modules/interventions/test_playbook_security_guards.py \
  tests/modules/interventions/test_risk_observability_metrics.py \
  --no-cov -rA)"

PROMTOOL_OUTPUT="$(${COMPOSE[@]} run --rm --no-deps --entrypoint promtool prometheus check rules /etc/prometheus/alerts.yml)"

popd >/dev/null

DAY0_UTC="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
DAY1="$(date -u -d "+1 day" +%Y-%m-%d)"
DAY3="$(date -u -d "+3 day" +%Y-%m-%d)"
DAY7="$(date -u -d "+7 day" +%Y-%m-%d)"

cat >"${OUT_FILE}" <<EOF
# F2 Playbooks Post-Release Day-0 Baseline

- Captured at (UTC): ${DAY0_UTC}
- Scope: F2.9 day-0 baseline capture
- Feature flag: interventions.auto_playbooks
- Mode: pre-pilot 1/3/7-day validation (not 7/14/30)

## Verification Snapshot

### Backend playbook checks

\`\`\`text
${BACKEND_TEST_OUTPUT}
\`\`\`

### Prometheus rules validation

\`\`\`text
${PROMTOOL_OUTPUT}
\`\`\`

## Review Schedule

- Day 1 review due: ${DAY1}
- Day 3 review due: ${DAY3}
- Day 7 review due: ${DAY7}

## KPI Tracking Checklist

- [ ] intervention_conversion_rate baseline recorded
- [ ] playbook_execution_latency_p95 baseline recorded
- [ ] auto_playbook_trigger_precision baseline recorded
- [ ] playbook_abandonment_rate baseline recorded
- [ ] PlaybookExecutionLatencyP95High alert noise reviewed
- [ ] PlaybookAbandonmentRateHigh alert noise reviewed
- [ ] Feature flag rollout phase (0/1/2/3) documented

## Notes

- This baseline is generated by scripts/f2_playbooks_post_release_day0.sh.
- Keep this artifact immutable; append follow-up findings in day-7/day-14/day-30 artifacts.
- Rollout runbook: docs/runbooks/F2_PLAYBOOKS_RELEASE_ROLLBACK.md
EOF

echo "[f2-day0] baseline artifact created: ${OUT_FILE}"
