#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COMPOSE=(docker compose --env-file .env)
ARTIFACTS_DIR="${ROOT_DIR}/docs/runbooks/artifacts"

usage() {
  cat <<EOF
Usage:
  bash scripts/f2_playbooks_post_release_day_review.sh --phase <day1|day3|day7> [--allow-early]

Options:
  --phase        Review phase to execute.
  --allow-early  Allow execution before due date (records EARLY_EXECUTION=true in artifact).
EOF
}

phase=""
allow_early="false"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --phase)
      phase="${2:-}"
      shift 2
      ;;
    --allow-early)
      allow_early="true"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "[f2-review] ERROR: unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

if [[ -z "${phase}" ]]; then
  echo "[f2-review] ERROR: --phase is required" >&2
  usage
  exit 1
fi

case "${phase}" in
  day1|day3|day7) ;;
  *)
    echo "[f2-review] ERROR: invalid phase '${phase}' (expected day1|day3|day7)" >&2
    exit 1
    ;;
esac

bash "${ROOT_DIR}/scripts/docker_only_guard.sh"

latest_day0="$(ls -1 "${ARTIFACTS_DIR}"/f2_playbooks_day0_baseline_*.md 2>/dev/null | tail -n 1 || true)"
if [[ -z "${latest_day0}" ]]; then
  echo "[f2-review] ERROR: day-0 baseline artifact not found. Run: bash scripts/f2_playbooks_post_release_day0.sh" >&2
  exit 1
fi

due_key=""
case "${phase}" in
  day1)  due_key="Day 1 review due" ;;
  day3) due_key="Day 3 review due" ;;
  day7)  due_key="Day 7 review due" ;;
esac

due_date="$(awk -F': ' -v key="${due_key}" '$0 ~ key {print $2; exit}' "${latest_day0}")"
if [[ -z "${due_date}" ]]; then
  echo "[f2-review] ERROR: failed to parse due date (${due_key}) from ${latest_day0}" >&2
  exit 1
fi

today_utc="$(date -u +%Y-%m-%d)"
if [[ "${allow_early}" != "true" && "${today_utc}" < "${due_date}" ]]; then
  echo "[f2-review] ERROR: phase ${phase} is not due yet (today=${today_utc}, due=${due_date}). Use --allow-early for rehearsal." >&2
  exit 1
fi

pushd "${ROOT_DIR}/infra" >/dev/null

BACKEND_TEST_OUTPUT="$(${COMPOSE[@]} run --rm --no-deps -e DATABASE_URL= backend-tests pytest -q \
  tests/modules/interventions/test_router_playbooks_phase2.py \
  tests/modules/interventions/test_playbook_security_guards.py \
  tests/modules/interventions/test_risk_observability_metrics.py \
  --no-cov -rA)"

PROMTOOL_OUTPUT="$(${COMPOSE[@]} run --rm --no-deps --entrypoint promtool prometheus check rules /etc/prometheus/alerts.yml)"

popd >/dev/null

STAMP="$(date -u +%Y%m%d_%H%M%S)"
OUT_FILE="${ARTIFACTS_DIR}/f2_playbooks_${phase}_review_${STAMP}.md"
FILLED_UTC="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
EARLY_FLAG="${allow_early}"

cat >"${OUT_FILE}" <<EOF
# F2 Playbooks Post-Release ${phase} Review

- Captured at (UTC): ${FILLED_UTC}
- Phase: ${phase}
- Due date: ${due_date}
- EARLY_EXECUTION: ${EARLY_FLAG}
- Day-0 baseline: ${latest_day0##*/}

## Verification Snapshot

### Backend playbook checks

\`\`\`text
${BACKEND_TEST_OUTPUT}
\`\`\`

### Prometheus rules validation

\`\`\`text
${PROMTOOL_OUTPUT}
\`\`\`

## KPI Delta Review

- [ ] intervention_conversion_rate delta vs day-0 baseline
- [ ] playbook_execution_latency_p95 trend
- [ ] auto_playbook_trigger_precision trend
- [ ] playbook_abandonment_rate trend
- [ ] Alert noise: PlaybookExecutionLatencyP95High, PlaybookAbandonmentRateHigh
- [ ] Feature flag rollout phase progression documented
- [ ] Tenant feedback / escalations reviewed

## Findings

*(Fill in during review)*

## Verdict

- [ ] PASS — continue rollout / no action needed
- [ ] CONDITIONAL — action items below
- [ ] FAIL — rollback triggered (run: bash scripts/f2_playbooks_post_release_gate.sh)

## Notes

- This artifact is generated by scripts/f2_playbooks_post_release_day_review.sh --phase ${phase}.
- Rollout/rollback runbook: docs/runbooks/F2_PLAYBOOKS_RELEASE_ROLLBACK.md
EOF

echo "[f2-review] artifact created: ${OUT_FILE}"
