#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ARTIFACTS_DIR="${ROOT_DIR}/docs/runbooks/artifacts"
STAMP="$(date -u +%Y%m%d_%H%M%S)"
OUT_FILE="${ARTIFACTS_DIR}/f1_risk_post_release_snapshot_${STAMP}.md"

mkdir -p "${ARTIFACTS_DIR}"

STATUS_OUTPUT="$(bash "${ROOT_DIR}/scripts/risk_phase_f1_post_release_status.sh")"

set +e
GATE_OUTPUT="$(bash "${ROOT_DIR}/scripts/risk_phase_f1_post_release_gate.sh" 2>&1)"
GATE_EXIT=$?
DUE_OUTPUT="$(bash "${ROOT_DIR}/scripts/risk_phase_f1_post_release_due_alert.sh" 2>&1)"
DUE_EXIT=$?
set -e

NOW_UTC="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

cat >"${OUT_FILE}" <<EOF
# F1 Risk Post-Release Snapshot

- Captured at (UTC): ${NOW_UTC}

## Status Output

\`\`\`text
${STATUS_OUTPUT}
\`\`\`

## Gate Output

- Exit code: ${GATE_EXIT}

\`\`\`text
${GATE_OUTPUT}
\`\`\`

## Due Alert Output

- Exit code: ${DUE_EXIT}

\`\`\`text
${DUE_OUTPUT}
\`\`\`

## Notes

- Snapshot generated by scripts/risk_phase_f1_post_release_snapshot.sh.
- Gate exit code 0 means F1.9 completion gate passed.
EOF

echo "[f1-snapshot] created: ${OUT_FILE}"