#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COMPOSE=(docker compose --env-file .env)
ARTIFACTS_DIR="${ROOT_DIR}/docs/runbooks/artifacts"
STAMP="$(date -u +%Y%m%d_%H%M%S)"
OUT_FILE="${ARTIFACTS_DIR}/f1_risk_day0_baseline_${STAMP}.md"

bash "${ROOT_DIR}/scripts/docker_only_guard.sh"
mkdir -p "${ARTIFACTS_DIR}"

pushd "${ROOT_DIR}/infra" >/dev/null

BACKEND_TEST_OUTPUT="$(${COMPOSE[@]} run --rm --no-deps -e DATABASE_URL= backend-tests pytest -q \
  tests/modules/interventions/test_risk_observability_metrics.py \
  tests/modules/interventions/test_router_interventions_risk_phasec.py::test_v1_recompute_scores_burst_profile_p95_under_slo \
  tests/test_rate_limit.py::test_risk_recompute_rate_limit_returns_429_and_audits \
  --no-cov -rA)"

PROMTOOL_OUTPUT="$(${COMPOSE[@]} run --rm --no-deps --entrypoint promtool prometheus check rules /etc/prometheus/alerts.yml)"

popd >/dev/null

DAY0_UTC="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
DAY1="$(date -u -d "+1 day" +%Y-%m-%d)"
DAY3="$(date -u -d "+3 day" +%Y-%m-%d)"
DAY7="$(date -u -d "+7 day" +%Y-%m-%d)"

cat >"${OUT_FILE}" <<EOF
# F1 Risk Post-Release Day-0 Baseline

- Captured at (UTC): ${DAY0_UTC}
- Scope: F1.9 day-0 baseline capture

## Verification Snapshot

### Backend risk checks

\`\`\`text
${BACKEND_TEST_OUTPUT}
\`\`\`

### Prometheus rules validation

\`\`\`text
${PROMTOOL_OUTPUT}
\`\`\`

## Review Schedule

- Day 1 review due: ${DAY1}
- Day 3 review due: ${DAY3}
- Day 7 review due: ${DAY7}

## KPI Tracking Checklist

- [ ] dropout_risk_reduction_percent delta recorded
- [ ] false_positive_rate calibration reviewed
- [ ] intervention_conversion_rate trend reviewed
- [ ] advisor_action_latency_p95 trend reviewed
- [ ] alert noise (RiskScoringJobFailureSpike / RiskScoringLatencyP95High / RiskPipelineStaleData) reviewed

## Notes

- This baseline is generated by scripts/risk_phase_f1_post_release_day0.sh.
- Keep this artifact immutable; append follow-up findings in day-7/day-14/day-30 artifacts.
EOF

echo "[f1-day0] baseline artifact created: ${OUT_FILE}"