import { apiGet, apiPatch, apiPost } from '@/shared/api/client';
import { QUALITY_ACCREDITATION_API_PATHS } from './constants';
import type {
  AccreditationRegistryRuntimeResponse,
  AccreditationCalendarCreatePayload,
  AccreditationCalendarItem,
  AccreditationCalendarUpdatePayload,
  AccreditationCommitteeWorkflow,
  AccreditationCommitteeWorkflowCreatePayload,
  AccreditationCommitteeWorkflowUpdatePayload,
  AccreditationStandard,
  AccreditationStandardCreatePayload,
  AccreditationStandardUpdatePayload,
  ComplianceGapAnalysis,
  ComplianceGapAnalysisCreatePayload,
  ComplianceGapAnalysisUpdatePayload,
  EvidenceLimitation,
  EvidenceLimitationCreatePayload,
  ExpertRecommendationResponsePlan,
  ExpertRecommendationResponsePlanCreatePayload,
  ExternalExpertReview,
  ExternalExpertReviewCreatePayload,
  ExternalExpertReviewUpdatePayload,
  InstitutionalReadiness,
  InstitutionalReadinessCreatePayload,
  InstitutionalReadinessUpdatePayload,
  InternalQualityAudit,
  InternalQualityAuditCreatePayload,
  InternalQualityAuditUpdatePayload,
  LearningOutcomesAssessment,
  LearningOutcomesAssessmentCreatePayload,
  LearningOutcomesAssessmentUpdatePayload,
  ProgramReadiness,
  ProgramReadinessCreatePayload,
  ProgramReadinessUpdatePayload,
  ProgramReviewCycle,
  ProgramReviewCycleCreatePayload,
  ProgramReviewCycleUpdatePayload,
  QualityAccreditationDashboardResponse,
  QualityAccreditationHealthResponse,
  QualityAccreditationLimitationsResponse,
  QualityAccreditationListResponse,
  QualityAccreditationMatrixSummaryResponse,
  QualityAccreditationOverviewResponse,
  QualityAccreditationRuntimeShellResponse,
  QualityAuditEvent,
  QualityAuditFinding,
  QualityAuditFindingCreatePayload,
  QualityAuditFindingUpdatePayload,
  QualityBrainSignal,
  QualityBrainSignalCreatePayload,
  QualityBridge,
  QualityBridgeCreatePayload,
  QualityEvidence,
  QualityEvidenceCreatePayload,
  QualityEvidenceReview,
  QualityEvidenceReviewPayload,
  QualityFramework,
  QualityFrameworkCreatePayload,
  QualityFrameworkUpdatePayload,
  QualityImprovementAction,
  QualityImprovementActionCreatePayload,
  QualityImprovementActionUpdatePayload,
  QualityImprovementPlan,
  QualityImprovementPlanCreatePayload,
  QualityImprovementPlanUpdatePayload,
  QualityRisk,
  QualityRiskCreatePayload,
  QualityRiskUpdatePayload,
  QualityStatusHistory,
  SelfAssessmentReport,
  SelfAssessmentReportCreatePayload,
  SelfAssessmentReportUpdatePayload,
  SelfAssessmentSection,
  SelfAssessmentSectionCreatePayload,
  SelfAssessmentSectionUpdatePayload,
  StakeholderFeedbackMetadata,
  StakeholderFeedbackMetadataCreatePayload,
  StandardCriterion,
  StandardCriterionCreatePayload,
  StandardCriterionUpdatePayload,
  StandardsEvidenceRequirement,
  StandardsEvidenceRequirementCreatePayload,
  SurveyQualityMetadata,
  SurveyQualityMetadataCreatePayload,
} from './types';

export const qualityAccreditationApi = {
  getQualityAccreditationRuntimeShell: () => apiGet<QualityAccreditationRuntimeShellResponse>(QUALITY_ACCREDITATION_API_PATHS.runtimeShell),
  getAccreditationRegistry: () => apiGet<AccreditationRegistryRuntimeResponse>(QUALITY_ACCREDITATION_API_PATHS.accreditationRegistry),
  getQualityAccreditationHealth: () => apiGet<QualityAccreditationHealthResponse>(QUALITY_ACCREDITATION_API_PATHS.health),
  getQualityAccreditationOverview: () => apiGet<QualityAccreditationOverviewResponse>(QUALITY_ACCREDITATION_API_PATHS.overview),
  getQualityAccreditationDashboard: () => apiGet<QualityAccreditationDashboardResponse>(QUALITY_ACCREDITATION_API_PATHS.dashboard),
  getQualityAccreditationMatrixSummary: () => apiGet<QualityAccreditationMatrixSummaryResponse>(QUALITY_ACCREDITATION_API_PATHS.matrixSummary),
  getQualityAccreditationLimitations: () => apiGet<QualityAccreditationLimitationsResponse>(QUALITY_ACCREDITATION_API_PATHS.limitations),

  listQualityFrameworks: () => apiGet<QualityAccreditationListResponse<QualityFramework>>(QUALITY_ACCREDITATION_API_PATHS.frameworks),
  createQualityFramework: (payload: QualityFrameworkCreatePayload) => apiPost<QualityFramework>(QUALITY_ACCREDITATION_API_PATHS.frameworks, payload),
  updateQualityFramework: (id: number | string, payload: QualityFrameworkUpdatePayload) => apiPatch<QualityFramework>(`${QUALITY_ACCREDITATION_API_PATHS.frameworks}/${id}`, payload),

  listAccreditationStandards: () => apiGet<QualityAccreditationListResponse<AccreditationStandard>>(QUALITY_ACCREDITATION_API_PATHS.standards),
  createAccreditationStandard: (payload: AccreditationStandardCreatePayload) => apiPost<AccreditationStandard>(QUALITY_ACCREDITATION_API_PATHS.standards, payload),
  updateAccreditationStandard: (id: number | string, payload: AccreditationStandardUpdatePayload) => apiPatch<AccreditationStandard>(`${QUALITY_ACCREDITATION_API_PATHS.standards}/${id}`, payload),

  listStandardCriteria: () => apiGet<QualityAccreditationListResponse<StandardCriterion>>(QUALITY_ACCREDITATION_API_PATHS.criteria),
  createStandardCriterion: (payload: StandardCriterionCreatePayload) => apiPost<StandardCriterion>(QUALITY_ACCREDITATION_API_PATHS.criteria, payload),
  updateStandardCriterion: (id: number | string, payload: StandardCriterionUpdatePayload) => apiPatch<StandardCriterion>(`${QUALITY_ACCREDITATION_API_PATHS.criteria}/${id}`, payload),

  listStandardsEvidenceRequirements: () => apiGet<QualityAccreditationListResponse<StandardsEvidenceRequirement>>(QUALITY_ACCREDITATION_API_PATHS.standardsEvidenceRequirements),
  createStandardsEvidenceRequirement: (payload: StandardsEvidenceRequirementCreatePayload) => apiPost<StandardsEvidenceRequirement>(QUALITY_ACCREDITATION_API_PATHS.standardsEvidenceRequirements, payload),

  listQualityEvidence: () => apiGet<QualityAccreditationListResponse<QualityEvidence>>(QUALITY_ACCREDITATION_API_PATHS.evidence),
  createQualityEvidence: (payload: QualityEvidenceCreatePayload) => apiPost<QualityEvidence>(QUALITY_ACCREDITATION_API_PATHS.evidence, payload),
  updateQualityEvidence: (id: number | string, payload: Partial<QualityEvidenceCreatePayload>) => apiPatch<QualityEvidence>(`${QUALITY_ACCREDITATION_API_PATHS.evidence}/${id}`, payload),
  reviewQualityEvidence: (id: number | string, payload: QualityEvidenceReviewPayload) => apiPost<QualityEvidenceReview>(`${QUALITY_ACCREDITATION_API_PATHS.evidence}/${id}/review`, payload),
  listEvidenceLimitations: () => apiGet<QualityAccreditationListResponse<EvidenceLimitation>>(QUALITY_ACCREDITATION_API_PATHS.evidenceLimitations),
  createEvidenceLimitation: (payload: EvidenceLimitationCreatePayload) => apiPost<EvidenceLimitation>(QUALITY_ACCREDITATION_API_PATHS.evidenceLimitations, payload),

  listProgramReadiness: () => apiGet<QualityAccreditationListResponse<ProgramReadiness>>(QUALITY_ACCREDITATION_API_PATHS.programReadiness),
  createProgramReadiness: (payload: ProgramReadinessCreatePayload) => apiPost<ProgramReadiness>(QUALITY_ACCREDITATION_API_PATHS.programReadiness, payload),
  updateProgramReadiness: (id: number | string, payload: ProgramReadinessUpdatePayload) => apiPatch<ProgramReadiness>(`${QUALITY_ACCREDITATION_API_PATHS.programReadiness}/${id}`, payload),
  listInstitutionalReadiness: () => apiGet<QualityAccreditationListResponse<InstitutionalReadiness>>(QUALITY_ACCREDITATION_API_PATHS.institutionalReadiness),
  createInstitutionalReadiness: (payload: InstitutionalReadinessCreatePayload) => apiPost<InstitutionalReadiness>(QUALITY_ACCREDITATION_API_PATHS.institutionalReadiness, payload),
  updateInstitutionalReadiness: (id: number | string, payload: InstitutionalReadinessUpdatePayload) => apiPatch<InstitutionalReadiness>(`${QUALITY_ACCREDITATION_API_PATHS.institutionalReadiness}/${id}`, payload),

  listSelfAssessmentReports: () => apiGet<QualityAccreditationListResponse<SelfAssessmentReport>>(QUALITY_ACCREDITATION_API_PATHS.selfAssessment),
  createSelfAssessmentReport: (payload: SelfAssessmentReportCreatePayload) => apiPost<SelfAssessmentReport>(QUALITY_ACCREDITATION_API_PATHS.selfAssessment, payload),
  updateSelfAssessmentReport: (id: number | string, payload: SelfAssessmentReportUpdatePayload) => apiPatch<SelfAssessmentReport>(`${QUALITY_ACCREDITATION_API_PATHS.selfAssessment}/${id}`, payload),
  listSelfAssessmentSections: () => apiGet<QualityAccreditationListResponse<SelfAssessmentSection>>(QUALITY_ACCREDITATION_API_PATHS.selfAssessmentSections),
  createSelfAssessmentSection: (payload: SelfAssessmentSectionCreatePayload) => apiPost<SelfAssessmentSection>(QUALITY_ACCREDITATION_API_PATHS.selfAssessmentSections, payload),
  updateSelfAssessmentSection: (id: number | string, payload: SelfAssessmentSectionUpdatePayload) => apiPatch<SelfAssessmentSection>(`${QUALITY_ACCREDITATION_API_PATHS.selfAssessmentSections}/${id}`, payload),

  listQualityImprovementPlans: () => apiGet<QualityAccreditationListResponse<QualityImprovementPlan>>(QUALITY_ACCREDITATION_API_PATHS.improvementPlans),
  createQualityImprovementPlan: (payload: QualityImprovementPlanCreatePayload) => apiPost<QualityImprovementPlan>(QUALITY_ACCREDITATION_API_PATHS.improvementPlans, payload),
  updateQualityImprovementPlan: (id: number | string, payload: QualityImprovementPlanUpdatePayload) => apiPatch<QualityImprovementPlan>(`${QUALITY_ACCREDITATION_API_PATHS.improvementPlans}/${id}`, payload),
  listQualityImprovementActions: () => apiGet<QualityAccreditationListResponse<QualityImprovementAction>>(QUALITY_ACCREDITATION_API_PATHS.improvementActions),
  createQualityImprovementAction: (payload: QualityImprovementActionCreatePayload) => apiPost<QualityImprovementAction>(QUALITY_ACCREDITATION_API_PATHS.improvementActions, payload),
  updateQualityImprovementAction: (id: number | string, payload: QualityImprovementActionUpdatePayload) => apiPatch<QualityImprovementAction>(`${QUALITY_ACCREDITATION_API_PATHS.improvementActions}/${id}`, payload),
  listInternalQualityAudits: () => apiGet<QualityAccreditationListResponse<InternalQualityAudit>>(QUALITY_ACCREDITATION_API_PATHS.internalAudits),
  createInternalQualityAudit: (payload: InternalQualityAuditCreatePayload) => apiPost<InternalQualityAudit>(QUALITY_ACCREDITATION_API_PATHS.internalAudits, payload),
  updateInternalQualityAudit: (id: number | string, payload: InternalQualityAuditUpdatePayload) => apiPatch<InternalQualityAudit>(`${QUALITY_ACCREDITATION_API_PATHS.internalAudits}/${id}`, payload),
  listQualityAuditFindings: () => apiGet<QualityAccreditationListResponse<QualityAuditFinding>>(QUALITY_ACCREDITATION_API_PATHS.auditFindings),
  createQualityAuditFinding: (payload: QualityAuditFindingCreatePayload) => apiPost<QualityAuditFinding>(QUALITY_ACCREDITATION_API_PATHS.auditFindings, payload),
  updateQualityAuditFinding: (id: number | string, payload: QualityAuditFindingUpdatePayload) => apiPatch<QualityAuditFinding>(`${QUALITY_ACCREDITATION_API_PATHS.auditFindings}/${id}`, payload),

  listProgramReviewCycles: () => apiGet<QualityAccreditationListResponse<ProgramReviewCycle>>(QUALITY_ACCREDITATION_API_PATHS.programReview),
  createProgramReviewCycle: (payload: ProgramReviewCycleCreatePayload) => apiPost<ProgramReviewCycle>(QUALITY_ACCREDITATION_API_PATHS.programReview, payload),
  updateProgramReviewCycle: (id: number | string, payload: ProgramReviewCycleUpdatePayload) => apiPatch<ProgramReviewCycle>(`${QUALITY_ACCREDITATION_API_PATHS.programReview}/${id}`, payload),
  listLearningOutcomesAssessments: () => apiGet<QualityAccreditationListResponse<LearningOutcomesAssessment>>(QUALITY_ACCREDITATION_API_PATHS.learningOutcomes),
  createLearningOutcomesAssessment: (payload: LearningOutcomesAssessmentCreatePayload) => apiPost<LearningOutcomesAssessment>(QUALITY_ACCREDITATION_API_PATHS.learningOutcomes, payload),
  updateLearningOutcomesAssessment: (id: number | string, payload: LearningOutcomesAssessmentUpdatePayload) => apiPatch<LearningOutcomesAssessment>(`${QUALITY_ACCREDITATION_API_PATHS.learningOutcomes}/${id}`, payload),
  listStakeholderFeedback: () => apiGet<QualityAccreditationListResponse<StakeholderFeedbackMetadata>>(QUALITY_ACCREDITATION_API_PATHS.stakeholderFeedback),
  createStakeholderFeedbackMetadata: (payload: StakeholderFeedbackMetadataCreatePayload) => apiPost<StakeholderFeedbackMetadata>(QUALITY_ACCREDITATION_API_PATHS.stakeholderFeedback, payload),
  listSurveyQualityMetadata: () => apiGet<QualityAccreditationListResponse<SurveyQualityMetadata>>(QUALITY_ACCREDITATION_API_PATHS.surveyQualityMetadata),
  createSurveyQualityMetadata: (payload: SurveyQualityMetadataCreatePayload) => apiPost<SurveyQualityMetadata>(QUALITY_ACCREDITATION_API_PATHS.surveyQualityMetadata, payload),

  listAccreditationCommitteeWorkflows: () => apiGet<QualityAccreditationListResponse<AccreditationCommitteeWorkflow>>(QUALITY_ACCREDITATION_API_PATHS.committee),
  createAccreditationCommitteeWorkflow: (payload: AccreditationCommitteeWorkflowCreatePayload) => apiPost<AccreditationCommitteeWorkflow>(QUALITY_ACCREDITATION_API_PATHS.committee, payload),
  updateAccreditationCommitteeWorkflow: (id: number | string, payload: AccreditationCommitteeWorkflowUpdatePayload) => apiPatch<AccreditationCommitteeWorkflow>(`${QUALITY_ACCREDITATION_API_PATHS.committee}/${id}`, payload),
  listExternalExpertReviews: () => apiGet<QualityAccreditationListResponse<ExternalExpertReview>>(QUALITY_ACCREDITATION_API_PATHS.externalReview),
  createExternalExpertReview: (payload: ExternalExpertReviewCreatePayload) => apiPost<ExternalExpertReview>(QUALITY_ACCREDITATION_API_PATHS.externalReview, payload),
  updateExternalExpertReview: (id: number | string, payload: ExternalExpertReviewUpdatePayload) => apiPatch<ExternalExpertReview>(`${QUALITY_ACCREDITATION_API_PATHS.externalReview}/${id}`, payload),
  listExpertResponsePlans: () => apiGet<QualityAccreditationListResponse<ExpertRecommendationResponsePlan>>(QUALITY_ACCREDITATION_API_PATHS.expertResponsePlans),
  createExpertRecommendationResponsePlan: (payload: ExpertRecommendationResponsePlanCreatePayload) => apiPost<ExpertRecommendationResponsePlan>(QUALITY_ACCREDITATION_API_PATHS.expertResponsePlans, payload),

  listComplianceGapAnalysis: () => apiGet<QualityAccreditationListResponse<ComplianceGapAnalysis>>(QUALITY_ACCREDITATION_API_PATHS.gapAnalysis),
  createComplianceGapAnalysis: (payload: ComplianceGapAnalysisCreatePayload) => apiPost<ComplianceGapAnalysis>(QUALITY_ACCREDITATION_API_PATHS.gapAnalysis, payload),
  updateComplianceGapAnalysis: (id: number | string, payload: ComplianceGapAnalysisUpdatePayload) => apiPatch<ComplianceGapAnalysis>(`${QUALITY_ACCREDITATION_API_PATHS.gapAnalysis}/${id}`, payload),
  listAccreditationCalendar: () => apiGet<QualityAccreditationListResponse<AccreditationCalendarItem>>(QUALITY_ACCREDITATION_API_PATHS.calendar),
  createAccreditationCalendarItem: (payload: AccreditationCalendarCreatePayload) => apiPost<AccreditationCalendarItem>(QUALITY_ACCREDITATION_API_PATHS.calendar, payload),
  updateAccreditationCalendarItem: (id: number | string, payload: AccreditationCalendarUpdatePayload) => apiPatch<AccreditationCalendarItem>(`${QUALITY_ACCREDITATION_API_PATHS.calendar}/${id}`, payload),
  listQualityRisks: () => apiGet<QualityAccreditationListResponse<QualityRisk>>(QUALITY_ACCREDITATION_API_PATHS.riskRegister),
  createQualityRisk: (payload: QualityRiskCreatePayload) => apiPost<QualityRisk>(QUALITY_ACCREDITATION_API_PATHS.riskRegister, payload),
  updateQualityRisk: (id: number | string, payload: QualityRiskUpdatePayload) => apiPatch<QualityRisk>(`${QUALITY_ACCREDITATION_API_PATHS.riskRegister}/${id}`, payload),

  listQualityBridges: () => apiGet<QualityAccreditationListResponse<QualityBridge>>(QUALITY_ACCREDITATION_API_PATHS.bridges),
  createQualityBridge: (payload: QualityBridgeCreatePayload) => apiPost<QualityBridge>(QUALITY_ACCREDITATION_API_PATHS.bridges, payload),
  listQualityBrainSignals: () => apiGet<QualityAccreditationListResponse<QualityBrainSignal>>(QUALITY_ACCREDITATION_API_PATHS.brainSignals),
  createQualityBrainSignal: (payload: QualityBrainSignalCreatePayload) => apiPost<QualityBrainSignal>(QUALITY_ACCREDITATION_API_PATHS.brainSignals, payload),
  listQualityAuditEvents: () => apiGet<QualityAccreditationListResponse<QualityAuditEvent>>(QUALITY_ACCREDITATION_API_PATHS.audit),
  listQualityStatusHistory: () => apiGet<QualityAccreditationListResponse<QualityStatusHistory>>(QUALITY_ACCREDITATION_API_PATHS.statusHistory),
};